### ISSUE TITLE
Add ifTime conditional

### ISSUE THREAD

**Issue by mrjoshida** [code-dot-org/dance-party#102]
The current conditional for checking elapsed time is complicated, replacing with `ifTime`
![image](https://user-images.githubusercontent.com/2744615/47937569-61b12b00-de9e-11e8-8dda-11cb94965b10.png)
https://levelbuilder-studio.code.org/blocks/Dancelab_ifTime/edit

**Comment by boatmarina** [comment]
this looks fixed now
