### ISSUE TITLE
PG-13 songs not showing up in list for over 13 users

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#105]
I'm logged in as a teacher, but don't see PG-13 songs (like Macklemore).  Ryan confirms this is a bug. :)

![image](https://user-images.githubusercontent.com/33850843/47946145-dbf4a600-dec4-11e8-8f82-5b1eefb4a009.png)

**Comment by ryansloan** [comment]
confirmed fixed with latest filtering work
