### ISSUE TITLE
After passing some levels, changing code and re-running doesn't allow you to fail

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#109]
ex: Puzzle 5

**Comment by boatmarina** [comment]
I think we can won't fix this, right @ryansloan ?  also, i passed level 5, went to the next level, and then back to 5, removed the code i wrote and it did fail so this might be working now after all (unless i'm misinterpreting the repro steps.)  either way, i think fixing this seems like not a high priority - doubt kids are going to want to go back to levels they've completed and break their code
