### ISSUE TITLE
Elapsed bock doesn't seem to effect anything

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#111]
not sure what the bug is, but i've tried this combo with measures elapsed = or > and doesn't seem to affect the dancer or the background

![image](https://user-images.githubusercontent.com/33850843/47972161-4c7afe80-e04e-11e8-94c0-3411f2b19c2b.png)
![image](https://user-images.githubusercontent.com/33850843/47972172-81875100-e04e-11e8-82bc-f08173d4f0e6.png)

**Comment by ryansloan** [comment]
The code inside setup runs one time, at which point 8 (or 2) measures have not elapsed

**Comment by ryansloan** [comment]
FYI @mrjoshida some programming model misunderstandings. closing but wanted you to see
