### ISSUE TITLE
Integrate short-burst animations for Alien and Pineapple

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#112]
i can't figure out what's makign this happen, but sometimes there are 3 or 4 cats even though i've made only 2.  it doesn't happen every time

![image](https://user-images.githubusercontent.com/33850843/47972275-8bf61a80-e04f-11e8-8fe4-de3d400d3d6a.png)

**Comment by boatmarina** [comment]
here is a time where there are 4 cats (and i didn't change any code):

![image](https://user-images.githubusercontent.com/33850843/47972311-b3e57e00-e04f-11e8-9916-6213727bfcea.png)

**Comment by ryansloan** [comment]
This is because the Alien and Pineapple don't have short moves yet. When we can't find a move for a character, it changes into a cat.

**Comment by ryansloan** [comment]
verified these files are in

**Comment by joshlory** [comment]
We should fix this manually in the short term, but issue https://github.com/code-dot-org/dance-party/issues/233 should be our plan for the long-term.

**Comment by joshlory** [comment]
Resolved by PR https://github.com/code-dot-org/dance-party/pull/241.
