### ISSUE TITLE
disable run button while loading

### ISSUE THREAD

**Issue by Bjvanminnen** [code-dot-org/dance-party#113]
![image](https://user-images.githubusercontent.com/1767466/48019708-ebeccf80-e0e8-11e8-91a9-b2a3a051a6dc.png)

It seems like it would be nice if we could disable our run button until the workspace has loaded

**Comment by boatmarina** [comment]
this seems like something we can won't fix at this point - we have improved loading times.  @ryansloan to see this in case he disagrees.
