### ISSUE TITLE
Background change doesn't happen if scheduled at same time as dance move

### ISSUE THREAD

**Issue by uponthesun** [code-dot-org/dance-party#120]
![dance-background-change](https://user-images.githubusercontent.com/6564873/48035894-c8db1380-e11a-11e8-8aac-bc6b913a5296.PNG)

Did this on Firefox.

**Comment by joshlory** [comment]
Nice find!

**Comment by epeach** [comment]
I believe this will have the same root cause as: https://github.com/code-dot-org/dance-party/issues/165

**Comment by ryansloan** [comment]
I documented expected behavior here: https://github.com/code-dot-org/dance-party/issues/165#issuecomment-436767586

**Comment by ryansloan** [comment]
I am going to close this as a dupe of #165 even though this one's older since there's more documentation and discussion in that thread
