### ISSUE TITLE
Shouldn't we have "view code" and "make my own" buttons on the share page?

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#123]
Why don't we have these buttons on the dance party share page (this picture is of a gamelab project):
![image](https://user-images.githubusercontent.com/33850843/48042188-57f52500-e135-11e8-9616-2a6c1890e398.png)

Here is a dance party project:
![image](https://user-images.githubusercontent.com/33850843/48042232-925ec200-e135-11e8-9368-abdf3c7a2a79.png)

**Comment by boatmarina** [comment]
is this related to not having the dance party projects turned on yet (and behind a flag?)

**Comment by breville** [comment]
I think we should do https://github.com/code-dot-org/dance-party/issues/395 instead and have prepped a fix for that.

**Comment by boatmarina** [comment]
Sounds good to me! Agree that this seems more prominent.

**Comment by breville** [comment]
Okay, I'll close this one then.
