### ISSUE TITLE
Sharing a project via header when logged out should not require login

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#124]
If you're not logged in, can we make the Share button pop up the dialog w/ the share URL instead of prompting you to login:

![image](https://user-images.githubusercontent.com/33850843/48042499-9b9c5e80-e136-11e8-8c78-eeccd78ea59c.png)

**Comment by ryansloan** [comment]
This works as desired in Artist, Playlab, Sprite Lab.

**Comment by breville** [comment]
Apparently the level needs to have the `is_project_level` property set to `true`, as checked [here](https://github.com/code-dot-org/code-dot-org/blob/staging/apps/src/code-studio/components/ShareDialog.jsx#L20).

The level in question [doesn't currently](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/config/scripts/levels/Dance_Party_12.level) have it.

**Comment by joshlory** [comment]
@breville `is_project_level` should only be set for standalone project levels, like `/p/artist` or `/p/dance`.  I agree the naming is confusing.  I believe there's another setting which controls whether the project can be shared while signed out.

Or it may be that we don't usually show the "Share" and "Remix" buttons in the header of a progression level.  I don't see them on https://studio.code.org/s/artist/stage/1/puzzle/10, only on App Lab or Game Lab levels that are channel-backed.

**Comment by breville** [comment]
@joshlory If you see the link I posted, it appears that `is_project_level` is the only flag we key off of: https://github.com/code-dot-org/code-dot-org/blob/staging/apps/src/code-studio/components/ShareDialog.jsx#L20

Do we need to add a new level property?

**Comment by ryansloan** [comment]
I tried this on Levelbuilder and it didn't seem to work. Setting this took away the buttons entirely:

<img width="1508" alt="screen shot 2018-11-08 at 12 16 04 pm" src="https://user-images.githubusercontent.com/1669271/48224888-1db39f80-e350-11e8-8de7-73971ce1823b.png">

(I switched it back to `false`)
