### ISSUE TITLE
Some of the new layouts don't apply

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#125]
criss-cross, border, inside square don't do anything to the sharks.  Column, random, etc work

![image](https://user-images.githubusercontent.com/33850843/48042869-76a8eb00-e138-11e8-9fef-88e05bb8ce96.png)

**Comment by ryansloan** [comment]
This is known - it's a deploy timing issue (Levelbuilder updates went out before dance-party version update) I'm holding on my plate until I can verify in Staging.

**Comment by boatmarina** [comment]
verified this is fixed.
