### ISSUE TITLE
Choosing older age causes full page reload

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#126]
Currently, on production, visiting a dance-party level for the first time loads a full set of assets.  Then an age popup is shown, and after choosing an older age (> 13?), the entire page is reloaded.

Not sure how bad this is, especially given browser caching, but it does seem like a lot of extra data transfer for a fairly common scenario.

**Comment by ryansloan** [comment]
I think we should fix this before HOC, but not blocking for launch

**Comment by ryansloan** [comment]
Combining this with newer bug #306 because it has updated repro information.
