### ISSUE TITLE
Remix when signed out doesn't work

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#127]
Start signed out.  Hit remix - goes to sign in page.  Sign in.  This lands you on the dashboard home page rather than the remixed project.

**Comment by boatmarina** [comment]
Other potential issues:  if you are logged in (and maybe have certain account permissions?), hitting remix doesn't actually take you to the project either

**Comment by boatmarina** [comment]
i'm seeing remix not work for these accounts:  marina+teacher@code.org; marina+elem@code.org

**Comment by ryansloan** [comment]
This seems to be fixed with the change to no longer require levelbuilder permissions on /p/dance, and we confirmed with Marina's accounts yesterday.
