### ISSUE TITLE
Memory bloat as you switch between many songs

### ISSUE THREAD

**Issue by Bjvanminnen** [code-dot-org/dance-party#128]
Got to https://studio.code.org/s/dance/stage/1/puzzle/13 and open up chrome task manager
Notice that the memory footprint of the process is < 200mb
Select a new song and watch the memory footprint climb
After going through the dropdown and selecting each of the songs, my memory footprint is at 1.2GB

I wonder if we can page some of this data out as we change songs.

**Comment by ryansloan** [comment]
This should be fixed w/  @davidsbailey's latest changes in code-dot-org: https://github.com/code-dot-org/code-dot-org/pull/25840

**Comment by davidsbailey** [comment]
Yep, this has been fixed on staging.
