### ISSUE TITLE
If a song fails to load, run button is permanently disabled

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#130]
Reported by @davidsbailey

**Comment by davidsbailey** [comment]
Repro steps:
1. load https://studio.code.org/s/dance/stage/1/puzzle/1
2. disconnect from the network (e.g. via chrome debug tools)
3. switch songs
4. press run
5. reconnect to the network

expected: reset button eventually becomes visible
actual: run button stays gray forever no matter what you do. page must be refreshed to recover
