### ISSUE TITLE
Cat Sprite dance 'ThisOrThat' slower than other sprites

### ISSUE THREAD

**Issue by epeach** [code-dot-org/dance-party#131]
![slowcat](https://user-images.githubusercontent.com/2959170/48083535-3e41f500-e1aa-11e8-8493-d04137d516bc.gif)

Repro - Lesson 13 - Starter code sprites. Set Cat and another sprite to dance 'ThisOrThat'. Press run.

Expected - Cat dances at same speed as other sprites.

Discovered on: Linux, Chrome 67

**Comment by ryansloan** [comment]
I think we must have bonus frames in the animation

**Comment by islemaster** [comment]
No repro on playground, so maybe not an asset problem? Investigating with reported repro on lesson 13.
![peek 2018-11-20 15-05](https://user-images.githubusercontent.com/1615761/48808479-cc06ff80-ecd5-11e8-9704-c65279309543.gif)

**Comment by islemaster** [comment]
I don't repro on puzzle 13 either, on local or production.  @epeach do you repro this anymore?
![peek 2018-11-20 15-09](https://user-images.githubusercontent.com/1615761/48808635-5cdddb00-ecd6-11e8-9f2f-a82a3b638eeb.gif)
