### ISSUE TITLE
Graphics are zoomed/centered strangely on certificates page

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#133]
I think these images are zoomed in (see the icons for follow on activities)

![image](https://user-images.githubusercontent.com/33850843/48081753-9e826800-e1a5-11e8-8656-0ca8aacc394c.png)

**Comment by boatmarina** [comment]
IE11 problem!

**Comment by ryansloan** [comment]
@boatmarina does it repro on all certificate pages?

**Comment by Erin007** [comment]
Doesn't repro on Chrome. 
<img width="1004" alt="screen shot 2018-11-07 at 3 56 01 pm" src="https://user-images.githubusercontent.com/12300669/48168824-c3f69b00-e2a5-11e8-81be-5f638b49b8fd.png">

**Comment by boatmarina** [comment]
does repro on other certificates (i tested minecraft):
![image](https://user-images.githubusercontent.com/33850843/48221667-8a766c00-e347-11e8-9a9f-ec3d248a62f8.png)

**Comment by boatmarina** [comment]
note, this doesn't repro in Edge.  and seems to be fine with the Minecraft image itself on the minecraft certificate.

**Comment by Erin007** [comment]
Fixed ✅ https://github.com/code-dot-org/code-dot-org/pull/25967
