### ISSUE TITLE
Set background color after x measures not working

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#135]
see this project code:
https://levelbuilder-studio.code.org/projects/dance/yDIfdH7QGDWE2R8_PhDi1w

but the background color is not changing

![image](https://user-images.githubusercontent.com/33850843/48086911-d512af80-e1b2-11e8-84b8-4281a22acd09.png)

**Comment by boatmarina** [comment]
repro in both IE and chrome

**Comment by joshlory** [comment]
Looks like this was also fixed by PR https://github.com/code-dot-org/dance-party/pull/88 🎉
