### ISSUE TITLE
level 3 (and others) too long to progress?

### ISSUE THREAD

**Issue by bakerfranke** [code-dot-org/dance-party#139]
after following instructions and running on this https://studio.code.org/s/dance/stage/1/puzzle/3 it takes a long time to know that I've completed the level.  With Carley Rae song I kept hitting reset because I didn't realize the song would end and give me the doo-doo-doo!. 

Is there a way to shortcut the song?

**Comment by ryansloan** [comment]
@mrjoshida do we want to reduce the measure delay?

**Comment by mrjoshida** [comment]
We could go from 12 to 10 and still have enough time to see the change. Would require a hints string change.

**Comment by mrjoshida** [comment]
Going to close for now, given that there's feedback that these are both too long and too short.
