### ISSUE TITLE
clarify instructions on level 6

### ISSUE THREAD

**Issue by bakerfranke** [code-dot-org/dance-party#141]
Level 6 instructions should explicitly say something like "use the `Make a new` block to create a dancer called 'backup_dancer1'".

Right now the purple block is preset to show "backup_dancer1"...which doesn't exist yet? and it made me (kid user) think all I had to do was add that block to my dance routine to see dancer show up.

**Comment by ryansloan** [comment]
@mrjoshida I don't think we can change this string at this point, but we can watch for user feedback.

**Comment by ryansloan** [comment]
We're closing this unless we find this to be a major issue - didn't manifest in play testing.
