### ISSUE TITLE
Autoprogess?

### ISSUE THREAD

**Issue by bakerfranke** [code-dot-org/dance-party#142]
Starting on or around level 7, you are enticed to hit run to watch the starter code, and/or only make a small change.  When the music ends the level automatically progresses (if I've done the basic task) without me clicking continue on the interstitial dialog.  i.o.w. it feels like a never see the sucesss/continue dialog.  It seems like click on the workspace is akin to hitting continue.  But I (kid user) am annoyed because I'm trying to modify my backup dancers that I just made!!!!!

**Comment by ryansloan** [comment]
@mrjoshida should we revisit the success condition? Or punt?

**Comment by ryansloan** [comment]
Ok, I was mostly reacting to this:

> you are enticed to hit run to watch the starter code, and/or only make a small change. When the music ends the level automatically progresses 

More than the popup thing. If we can't really check for success in a way that's more robust then I think this is a won't fix (we can't rebuild the continue dialog stuff right now.)
