### ISSUE TITLE
Fail message on level 9 - "right unicorn?"

### ISSUE THREAD

**Issue by bakerfranke** [code-dot-org/dance-party#143]
Should the failure message in instruction area say "right unicorn" instead of pineapple?
![image](https://user-images.githubusercontent.com/11284819/48093257-7eb66880-e1d4-11e8-8db3-adc2e7aae1c1.png)

**Comment by ryansloan** [comment]
This is in progress https://github.com/code-dot-org/code-dot-org/pull/25820
