### ISSUE TITLE
terminology: begins...folllowing

### ISSUE THREAD

**Issue by bakerfranke** [code-dot-org/dance-party#145]
I find the block: `[character] beings [property] following [music]` unintuitive.   Can we use some version of the word 'change' instead?

alternatives:
**set** [character] **to change** [property] **with** [music]
even
[character] **changes** [property] **following** [music]

**Comment by ryansloan** [comment]
This is good feedback, but the ship has sailed on the strings for HOC. Given that it's in block definitions, we could change post-HOC but we are already localizing these.
