### ISSUE TITLE
Level 11 - "high clap" == "clap high"

### ISSUE THREAD

**Issue by bakerfranke** [code-dot-org/dance-party#149]
Level 11 slight inconsistency in instruction to "....and "high clap" once when you press the up arrow key."  Pull down menu for dance moves has "Clap High".  Which makes it hard to find if you are used to this menu in alpha order.

**Comment by ryansloan** [comment]
We can potentially change this string post launch day when we have time to do another turn of the crank on translations, but this is a won't fix right now.

**Comment by joshlory** [comment]
Changing the string in English shouldn't break the existing translation in other locales, as long as the key doesn't change — right @Hamms?

This seems like something we should fix.

**Comment by Hamms** [comment]
Correct!

**Comment by ryansloan** [comment]
I changed instructions in LB.
