### ISSUE TITLE
Update Z-ordering

### ISSUE THREAD

**Issue by dmcavoy** [code-dot-org/dance-party#154]
<img width="323" alt="screen shot 2018-11-06 at 4 29 45 pm" src="https://user-images.githubusercontent.com/208083/48094845-3a7d9500-e1e1-11e8-984b-ba2bc8284e6c.png">

Create this

<img width="415" alt="screen shot 2018-11-06 at 4 30 22 pm" src="https://user-images.githubusercontent.com/208083/48094866-48331a80-e1e1-11e8-87f1-75869f033297.png">

**Comment by joshlory** [comment]
I think right now we sort dancers that are higher on the screen as behind dancers that are lower.  Maybe we should take size into account as well?

I'm not sure what z-order I'd expect, if the dancers were upright instead of fanned out in a circle.

**Comment by breville** [comment]
Possible fix at https://github.com/code-dot-org/dance-party/pull/447
