### ISSUE TITLE
change dance speed block broken

### ISSUE THREAD

**Issue by dmcavoy** [code-dot-org/dance-party#155]
<img width="846" alt="screen shot 2018-11-06 at 4 32 45 pm" src="https://user-images.githubusercontent.com/208083/48095037-b081fc00-e1e1-11e8-9c73-2749f5a42043.png">

**Comment by dmcavoy** [comment]
Also it freezes run if you put it in and try to run with it

**Comment by ryansloan** [comment]
@nkiruka if this isn't well-understood, we can also remove this block before launch. (it's not required for any puzzles, and we can always add later) LMK what you think the best course of action is.

**Comment by mrjoshida** [comment]
Looks like the bug was a problem with the default selection. I've fixed it and it appears to be working. I don't know whether it is in the translation pipeline though.

**Comment by Hamms** [comment]
This string is in the push to bureau.

Just to make sure everyone's on the same page, though, there are actually two completely separate issues here. The one issue of the string being in the loc push, and another issue entirely where it shows up broken on the client.

@nkiruka do we have an understanding of why the second issue happened?

**Comment by ryansloan** [comment]
@hamms @nkiruka I opened up a second issue to track that second thing, since it's a general issue and not with this block. #231 in the next milestone
