### ISSUE TITLE
repeat loop does not repeat action

### ISSUE THREAD

**Issue by dmcavoy** [code-dot-org/dance-party#159]
<img width="352" alt="screen shot 2018-11-06 at 4 43 04 pm" src="https://user-images.githubusercontent.com/208083/48095565-128f3100-e1e3-11e8-8a66-3399fdbb2f50.png">

The above code would only result in dancer doing the move once each 2 measures not 4 times. Tested it and go the same behavior if just remove repeat. Also same problem occurs for this code.

<img width="341" alt="screen shot 2018-11-06 at 4 45 30 pm" src="https://user-images.githubusercontent.com/208083/48095702-6437bb80-e1e3-11e8-8882-c534461f5fbd.png">

**Comment by ryansloan** [comment]
This is a consequence of the programming model, which is based on the same draw loop idea of Game Lab. I think at this point we've gone through a one-way door on this, but I wanted you to see it @mrjoshida

**Comment by mrjoshida** [comment]
Now that we have a `create <n> dancers` block I don't think there's a good application for repeat blocks, so we should just pull from the toolbox

**Comment by mrjoshida** [comment]
Removed
