### ISSUE TITLE
Reaching the end of the song should stop execution

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#16]

**Comment by epeach** [comment]
@ryansloan I think it makes sense go back to the initial white screen here and change the 'Reset' button to 'Run' - which basically mimics a 'Reset' click. Thoughts?

**Comment by epeach** [comment]
https://github.com/code-dot-org/code-dot-org/pull/25516

**Comment by ryansloan** [comment]
> @ryansloan I think it makes sense go back to the initial white screen here and change the 'Reset' button to 'Run' - which basically mimics a 'Reset' click. Thoughts?

@epeach Sorry, just saw this. That sounds good to me!
