### ISSUE TITLE
The ifDanceIs block is showing dance numbers, not dance names

### ISSUE THREAD

**Issue by islemaster** [code-dot-org/dance-party#164]
![screenshot from 2018-11-06 17-36-49](https://user-images.githubusercontent.com/1615761/48106404-28efb980-e1f0-11e8-8f60-c77d39d61795.png)

Visible in the Logic category of level 13 (free-play).

**Comment by ryansloan** [comment]
@islemaster I don't repro this - are you still seeing this? Was it on prod or dev? Do any other blocks have bad dropdowns?

**Comment by islemaster** [comment]
Sorry, this was on dev.  I should have investigated a bit more before filing.  Checking it out in different environments now...

**Comment by islemaster** [comment]
Yeah, I only repro local.  Closing...
