### ISSUE TITLE
Should last puzzle have a name?

### ISSUE THREAD

**Issue by Bjvanminnen** [code-dot-org/dance-party#170]
Because the last level has no name, we end up seeing a "n minutes since last saved" without any text atop it, which ends up looking like somewhat random text just floating there. Prob low pri.

![image](https://user-images.githubusercontent.com/1767466/48149529-284b3780-e271-11e8-9029-4c7055a5c144.png)

By comparison, on a level where we do have a name
![image](https://user-images.githubusercontent.com/1767466/48149546-36995380-e271-11e8-83ef-84bfd623c881.png)

**Comment by ryansloan** [comment]
Fixed on LB
