### ISSUE TITLE
Block not translated correctly in Spanish (mexico)

### ISSUE THREAD

**Issue by joshlory** [code-dot-org/dance-party#171]
![image](https://user-images.githubusercontent.com/413693/48152259-36e91d00-e278-11e8-9861-2a478e01e554.png)

**Comment by joshlory** [comment]
Another:

![image](https://user-images.githubusercontent.com/413693/48152444-c2fb4480-e278-11e8-9d47-84baf1158010.png)

**Comment by ryansloan** [comment]
@jakebrbell has fixed in crowdin
