### ISSUE TITLE
Level 3 - bad validation

### ISSUE THREAD

**Issue by mikeharv** [code-dot-org/dance-party#176]
If you set the duck to clap high after 6 measures it 1) starts one-side kicking animation instead of a clap and 2) fails validation. (You need to use a different dance.) This happens with all available dancers, not just the duck.

You can also pass the level by setting the duck to dab after 6 measures, even though that's the same dance assigned at 4 measures.

**Comment by mikeharv** [comment]
![image](https://user-images.githubusercontent.com/43474485/48161303-36687a80-e2a8-11e8-9c50-06db56ada19d.png)

**Comment by mikeharv** [comment]
This seems to be two separate issues:

- Clap high animation is broken all around
- Level 3 validation seems broken

**Comment by joshlory** [comment]
Duplicate of https://github.com/code-dot-org/dance-party/issues/167 I think.

**Comment by ryansloan** [comment]
Separating out. The clap is a dupe, but the validation is a separate issue.

**Comment by ryansloan** [comment]
I can't repro this - @mikeharv can you capture a gif of what you're seeing, and send browser info?

**Comment by mikeharv** [comment]
Now I can't repro either. Sorry!
