### ISSUE TITLE
IE 11: foreground effect "tacos" have transparent gray outlines

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#18]

**Comment by joshlory** [comment]
Screenshot?

Also: this effect likely won't work on exported video, without some major work.  (Thanks @Hamms for calling this out!)

**Comment by Hamms** [comment]
I'd also be interested to see what happens if the user is using a custom browser font

**Comment by ryansloan** [comment]
@mrjoshida I don't think we can do this - some of the browsers we support don't support emoji

**Comment by ryansloan** [comment]
Won't Fix. this looks fine in IE11 on modern versions of windows, it seems to be bad on Win7 IE11. This is a very small fraction of our users, and it's been a hit for the users who are on browsers that support it.
