### ISSUE TITLE
Level 12 - new_dancer or left_dancer?

### ISSUE THREAD

**Issue by mikeharv** [code-dot-org/dance-party#182]
This level is about the new group commands but it looks to have a set of single dancer commands cloned from a previous level. We should set the default value in each of these to "new_dancer" to match the `make a new` block, but also because "left_dancer" doesn't make sense in this context.
![image](https://user-images.githubusercontent.com/43474485/48162348-d2938100-e2aa-11e8-9186-df0ecb9db90a.png)

**Comment by ryansloan** [comment]
@mrjoshida will update dancer names in toolbox

**Comment by mrjoshida** [comment]
Updated toolbox here and in 11 to use "new_dancer"
