### ISSUE TITLE
student loses project code (final level) when signing in to share

### ISSUE THREAD

**Issue by bpcb** [code-dot-org/dance-party#198]
If a student goes through the DanceParty tutorial anonymously and then wants to share the dance project they created in the final level, they are prompted to create an account.  Clicking "Create Account" and then signing in takes the user to their Dashboard page.  If they return to the final puzzle level, their project code is gone.

Steps to reproduce (macOS, Safari Private Window)
1) Start DanceParty tutorial anonymously (in a private browser window), working each puzzle in order
2) Spend some time making an awesome dance on the final level (13)
3) Click "Share" in the upper-left and see prompt to "Create Account" because you must be logged in to share a project
4) Click "Create Account" to view Sign Up page
5) Click "Sign In" link and enter username/password of an existing student account who is over 13 years old.

Expected:  return to puzzle 13 with Share popup
Actual: Student Dashboard is displayed

6) Click browser back button to return to final DanceParty puzzle

Expected: see all the awesome code that you wrote
Actual: your code is gone and the code displayed is the start/template code for the puzzle

**Comment by bpcb** [comment]
contact @sureshc for more info

**Comment by ryansloan** [comment]
Once we fix #124 this should no longer be an issue (sign in will not appear in Share Dialog)
