### ISSUE TITLE
Serve song manifest from S3 instead of hard-coding

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#20]
A couple requirements:

- We need to be able to update the manifest periodically as new tracks are released
- Keep the manifest download size small-ish. (Sounds like this is in plan, and we'll store the track metadata in another file, just want to capture)

**Comment by ryansloan** [comment]
[Dev Spec](https://docs.google.com/document/d/16xiyt3gw7XhEcN3hoadejib2iiZwvYTzns0Y2-yCbqk/edit)

**Comment by epeach** [comment]
https://github.com/code-dot-org/code-dot-org/pull/25499
