### ISSUE TITLE
music continues after success popup after several run/reset passes

### ISSUE THREAD

**Issue by brook-osborne** [code-dot-org/dance-party#201]
chrome, mac. level 8

what happens: music played for 8 measures. success pop up showed, but music continued until you navigate to a new level. 

steps: 
- run and stop several times, changing tint color each time. 
- select a tint color and hit run -- this time you are going to let it run through. 
- in the first couple of measures, select a new song from the dropdown. 
- allow to play through the full 8 measures.

**Comment by brook-osborne** [comment]
[shaky cam cellphone video](https://youtu.be/ShE_fvpfn90) documenting repro steps and bug on level 8

**Comment by ryansloan** [comment]
@brook-osborne thank you for including the video! I think this is the same issue as #190 , marking duplicate but we will verify both scenarios when testing the fix.
