### ISSUE TITLE
not clear that you can't have multiple when<key> blocks for the same event

### ISSUE THREAD

**Issue by brook-osborne** [code-dot-org/dance-party#202]
chrome, mac. level 10

level doesn't make it clear that this won't work:
<img width="365" alt="screen shot 2018-11-07 at 8 35 24 pm" src="https://user-images.githubusercontent.com/30129449/48172232-17c8aa80-e2cd-11e8-96de-961b24f7987c.png">

i suspect students will try to string together multiple actions for the same event in this ^^ way.

**Comment by ryansloan** [comment]
I _think_ this is the same underlying issue as #165 @epeach , does that seem right to you?

**Comment by joshlory** [comment]
I didn't notice on first read that the first block said `left_dancer` and the second said `right_dancer`!

Yes, I think this is the final case in https://github.com/code-dot-org/dance-party/issues/165#issuecomment-436775298, equivalent to:

```
After 1 measure set the background to "orange".
After 1 measure set the foreground effect to "lights".
```

There is no conflict, and both should take effect.

**Comment by ryansloan** [comment]
Duping to #165
