### ISSUE TITLE
level 12 toolbox layout

### ISSUE THREAD

**Issue by brook-osborne** [code-dot-org/dance-party#204]
there are a bunch of blocks in the toolbox for left_dancer that block these three blocks from showing up above the fold: 
<img width="233" alt="screen shot 2018-11-07 at 8 44 42 pm" src="https://user-images.githubusercontent.com/30129449/48172471-fddb9780-e2cd-11e8-8374-99b9629878f3.png">

recommend reordering such that everything that could be used with 'all ducks' shows up before getting to the blocks that are for individual dancers

**Comment by mrjoshida** [comment]
Changed to category mode and added a callout to the "Groups" category
