### ISSUE TITLE
GIF share in Facebook feed

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#212]
Facebook will cache the 404/static thumbnail if the GIF isn't ready. If we do this, we need to add progress UI to block sharing until the video is ready. That needs to be spec'd.

We also need to make sure that OG Image GIFs work (Tanya had some promising investigations, we should verify that it works.)

**Comment by joshlory** [comment]
Based on @Hamms's investigation, I think this is cut?

**Comment by simplycloud** [comment]
I think we made a call today to have the Facebook share use the project thumbnail. We are going to have @Hamms move to looking at feasibility of adding a download option for the .mp4.
