### ISSUE TITLE
Dance Party Thumbnail work 

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#213]
- [x] Dance party generates thumbnails (prerequisite for project gallery)
_CUT: Optimize Files API for Dance Party thumbnails_

(We are moving everything from the spreadsheet over, these aren't new Work Items. I think Maddie is already working on these!)

**Comment by madelynkasula** [comment]
Implemented in [code-dot-org](https://github.com/code-dot-org/code-dot-org/pull/25748)
