### ISSUE TITLE
Point to translated versions of unplugged activity and lesson plan from /dance page

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#214]
Needed so unplugged and lesson plans can show up translated.  Blocked on list of languages we need to do this for (will need to get this from Jake).

Moving this over to Github instead of spreadsheet.

**Comment by ryansloan** [comment]
@boatmarina what's the need by date here? Launch or CS Ed Week?

**Comment by ryansloan** [comment]
@boatmarina do we know roughly what the ETA will be? (trying to sequence work)

**Comment by boatmarina** [comment]
Let's add these languages for now.  and do a separate sync once we have more languages:
Spanish (Mexico), Spanish (Spain), French, Korean, Turkish, Chinese (Traditional)

**Comment by boatmarina** [comment]
Updating title of this and assigning to Nkiru.  Turns out adding additional languages to curriculum builder doesn't work because if we do this, ALL of the CB content tries to point to translated versions of documents (which don't exist for most of our CB content) and creates broken links.  

Instead, going to fix in one of 2 ways.  Option 1 (preferred user experience): add logic to the lesson plan and unplugged activity tiles that checks for language of the page and changes the links to point directly to the translated version for that language.  Option 2 (also OK if option 1 is too risky):  add links to the english versions of these CB documents that point to the translated versions.

**Comment by nkiruka** [comment]
[PR 26193](https://github.com/code-dot-org/code-dot-org/pull/26193)

Option 1 was implemented

@boatmarina For some of the languages, the translated version is not available.  I will follow up with Jake

**Comment by simplycloud** [comment]
@nkiruka did this go out yesterday?

**Comment by nkiruka** [comment]
@simplycloud It's going out today.  I wanted to verify that the unplugged translations were in and that the lesson plan will be visible today.
