### ISSUE TITLE
Background Polish

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#215]
- [x] The Song Title background is unreadable with pastel colors. Try black background for this, with text in color (fixed in #297)

- [x] Bubbles background starts great but the bubbles get too big and over time the whole screen is one big bubble. Fix z-ordering so newer bubbles are on top.

**Comment by boatmarina** [comment]
can we make the "smaller" bubbles go into the front z-order layer?  @simplycloud tagging you as part of the background push

**Comment by simplycloud** [comment]
both fixes are out. thanks @Bjvanminnen!
