### ISSUE TITLE
Support for 'on click' events

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#219]
Need to account for large transparencies around the characters. (Sprite Lab handles this poorly right now, which is why our characters are compact)

**Comment by mrjoshida** [comment]
I would have expected [sprite.overlapPixel](https://code-dot-org.github.io/p5.play/docs/classes/Sprite.html#method-overlapPixel) to be an easy solution to this, but it looks like there's a bug - see project - https://studio.code.org/projects/gamelab/68uF7evE4OERTvSNarbNEQ/edit
