### ISSUE TITLE
Sign in button text misaligned

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#230]
the sign in button text is 1 pixel too high compared to all other labels.  this is only when signed out.  doesn't repro when signed in.

![image](https://user-images.githubusercontent.com/33850843/48277958-0ed8f580-e401-11e8-849e-d1d6f69bd88a.png)

**Comment by ryansloan** [comment]
@boatmarina will follow-up with @Erin007

**Comment by Erin007** [comment]
@boatmarina do you know if this is on Pegasus or Dashboard or both?

**Comment by boatmarina** [comment]
Just when signed out. Signed in looks fine. Only fix this if it’s easy!

**Comment by Erin007** [comment]
https://github.com/code-dot-org/code-dot-org/pull/25961
