### ISSUE TITLE
rand() doesn't work for short burst moves

### ISSUE THREAD

**Issue by cpirich** [code-dot-org/dance-party#234]
This recently regressed. I'm adding a test case that will catch this. @epeach

**Comment by joshlory** [comment]
Do you know where this regressed?

**Comment by epeach** [comment]
I believe this regressed when I added getNewChangedMove for both doMove and changeMove.

**Comment by ryansloan** [comment]
I have removed `random` from the `doMoveLR` and `doMoveEachLR` block definitions for now.

**Comment by cpirich** [comment]
https://github.com/code-dot-org/dance-party/pull/299

**Comment by cpirich** [comment]
Re-opening until we publish and merge this into the cdo-repo

**Comment by ryansloan** [comment]
fixed.
