### ISSUE TITLE
Consider adding kill switch for dance-extras

### ISSUE THREAD

**Issue by davidsbailey** [code-dot-org/dance-party#236]
Per discussion with @sureshc , we may want to have a couple dials and knobs in place to protect the `storage_apps` table in pegasus. The /s/dance script has some protections in place to alleviate pressure on this table, but /s/dance-extras is project-heavy and does not have these protections. The kill switch would need to hide the link to /s/dance-extras on https://code.org/dance . 

CC @simplycloud who is pushing for not worrying too much about these kinds of work items.

**Comment by joshlory** [comment]
PR https://github.com/code-dot-org/code-dot-org/pull/25902.
