### ISSUE TITLE
Hourofcode activities page graphic isn't bottom aligned

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#238]
When translated, and the text reflows, the paint splatter looks funny because it's not bottom aligned

![image](https://user-images.githubusercontent.com/33850843/48294406-d94ffe80-e438-11e8-9e28-a62712c7eaad.png)

**Comment by breville** [comment]
Known issue that has existed on /learn for certain screen widths for over a year now, and possibly since it was created.  So, we can fix it, but not sure how high a priority it is.  cc @tanyaparker

**Comment by tanyaparker** [comment]
@boatmarina I don't think this bug is as serious as tutorial bugs.

**Comment by boatmarina** [comment]
ok.  let's won't fix this.  sounds like there isn't a super straightforward fix for this.
