### ISSUE TITLE
Update links to tutorial videos to the generic music versions 

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#247]
we are still working on getting a license to use music in our tutorial videos.  until then, we need to use generic music that we have licenses for.  Here are the generic music versions of the tutorials.  we need to use these when we launch and can only swap in the ones w/ the real songs if we get the licenses.

Dance Party - Warm Up: https://youtu.be/bVHSrWuROrk

Dance Party - Events: https://youtu.be/ZyKRim_2Sm8

Dance Party - Properties: https://youtu.be/Dq3HovyOmvg

Dance Party - Party On! : https://youtu.be/pIxdBhJb8lc

The reduced size versions are here for people to download: https://www.dropbox.com/sh/fibe4dvu0fnss54/AAA37xVI2hrfsnbHxiU9k9Hpa?dl=0

(do we link to the downloadable versions of these videos anywhere?)

**Comment by ryansloan** [comment]
This is already done
