### ISSUE TITLE
Hints don't parse markdown

### ISSUE THREAD

**Issue by mrjoshida** [code-dot-org/dance-party#259]
(not technically a dance-party bug, but adding here so it's tracked) Some of our hints use backticks to style code blocks, but it looks like we don't support markdown there.

![image](https://user-images.githubusercontent.com/2744615/48368933-edc70d80-e669-11e8-9f1a-6173b596ba27.png)

**Comment by boatmarina** [comment]
how do you guys feel about won't fix'ing this for dance party?  does this affect how translations would work (do these get redacted?)

**Comment by boatmarina** [comment]
here is what this looks like in another language:
spanish:
![image](https://user-images.githubusercontent.com/33850843/48622411-8c4dba00-e95b-11e8-9b3d-10ec14fa3e65.png)

russian (I think russian translators did this a bit differently intentionally)
![image](https://user-images.githubusercontent.com/33850843/48622392-73450900-e95b-11e8-8641-a620fe4f5007.png)

given that this doesn't seem to affect translations, i'm marking this as won't fix.
