### ISSUE TITLE
Use Dance Party thumbnail for Facebook and Twitter share image

### ISSUE THREAD

**Issue by poorvasingal** [code-dot-org/dance-party#261]
Currently, share on FB gives you the default image for Dance Party:
![image](https://user-images.githubusercontent.com/16227893/48369341-1d2a4a00-e66b-11e8-9c4a-fb047e08139e.png)

We'd like it instead to show the project thumbnail:
![image](https://user-images.githubusercontent.com/16227893/48369356-274c4880-e66b-11e8-95ed-eb99932752d1.png)

P2: The default thumbnail we use for projects that don't have a generated thumbnail is this:
![image](https://user-images.githubusercontent.com/16227893/48369388-3a5f1880-e66b-11e8-93c3-165bb312aad8.png)

Ideally for Dance Party, we can make the default image be the Dance Party specific thumbnail instead.

**Comment by poorvasingal** [comment]
@ryansloan - I talked to Marina and we think that swapping out the generic thumbnail isn't a must-have to ship this since it'll be a rare scenario that the student tries sharing on FB without running the project.

**Comment by islemaster** [comment]
Related to https://github.com/code-dot-org/dance-party/issues/388

**Comment by islemaster** [comment]
Update: We'd like to do this for Twitter too, since embedded videos aren't working out as well as we'd like.

**Comment by poorvasingal** [comment]
Also, if we can't figure out the flakiness issue, I would bump up the P2 in this issue to a P1. In fact, I don't think we should ship this at all if we can't replace the teal thumbnail fallback with the Dance Party specific one.

**Comment by Erin007** [comment]
partial fix in https://github.com/code-dot-org/code-dot-org/pull/26168 <-uses a Dance Party specific placeholder, rather than the teal arrow, for Dance Party projects without thumbnails

**Comment by Erin007** [comment]
potential fix https://github.com/code-dot-org/code-dot-org/pull/26195 <- open concerns as this is hard to test across environments
