### ISSUE TITLE
"Jump" glitchy frames

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#263]
I have removed from the block for Launch Day, but we should fix for CS Ed Week

**Comment by joshlory** [comment]
Repros on [the playground](https://code-dot-org.github.io/dance-party/) with:

```js
nativeAPI.doMoveEachLR('all', 14, 1);
```

**Comment by islemaster** [comment]
This was a dumb mistake: https://github.com/code-dot-org/dance-spritesheets/commit/a1c57d911dc6e6a76c7836aab87c4324ea2e3b60

Working on a change with updated assets now.

**Comment by islemaster** [comment]
Fix is scheduled for the next deploy (sans block changes)

**Comment by islemaster** [comment]
Change merged, leaving this open pending block updates. (Assigning to Ryan)

**Comment by ryansloan** [comment]
Updated the block in levelbuilder. We won't scoop until we also scoop the Background block updates in the next push.
