### ISSUE TITLE
dance-extras levels should have titles

### ISSUE THREAD

**Issue by Bjvanminnen** [code-dot-org/dance-party#265]
https://levelbuilder-studio.code.org/s/dance-extras/stage/1/puzzle/6

![image](https://user-images.githubusercontent.com/1767466/48372551-cd9c4c00-e673-11e8-9531-6f67417aefc6.png)

I think we fixed this elsewhere, but the "saved n minutes ago" looks odd when we don't have a level name.

**Comment by ryansloan** [comment]
fixed in levelbuilder
