### ISSUE TITLE
Names should be capitalized in dance-extras level

### ISSUE THREAD

**Issue by Bjvanminnen** [code-dot-org/dance-party#266]
https://levelbuilder-studio.code.org/s/dance-extras/stage/1/puzzle/6

![image](https://user-images.githubusercontent.com/1767466/48372601-edcc0b00-e673-11e8-927f-d328db5fc088.png)

Pretty nitty, and fine if we won't fix, but it feels strange to me that we're not capitalizing the names of these characters, especially given we capitalize the type (i.e. Bear/Robot/Cat)

**Comment by boatmarina** [comment]
@mrjoshida if you're still tweaking strings in dance-extras, go for it. otherwise, please mark as won't fix.

**Comment by mrjoshida** [comment]
We don't capitalize variable names anywhere else (including in the first hour, where use use vars like `ducky`), so I'm gonna call this won't fix.
