### ISSUE TITLE
update dance party 2 tile on /congrats

### ISSUE THREAD

**Issue by tanyaparker** [code-dot-org/dance-party#278]
![image](https://user-images.githubusercontent.com/1920530/48376108-c62e7000-e67e-11e8-8970-96e34785aeb5.png)

Mark says this is supposed to be the moose and frog instead of cat and shark. Do you need that asset? It should also link to studio.code.org/s/dance-extras/reset so it goes to the first level instead of the course overview page.

**Comment by Erin007** [comment]
https://github.com/code-dot-org/code-dot-org/pull/25754
