### ISSUE TITLE
Twitter handles not showing up for Ariana Grande and Katy Perry

### ISSUE THREAD

**Issue by poorvasingal** [code-dot-org/dance-party#280]
CC @Erin007

**Comment by Erin007** [comment]
Fix in: https://github.com/code-dot-org/code-dot-org/pull/26060

**Comment by Erin007** [comment]
There's a cache on Twitter's end so this might not show up immediately even when the change hits prod. We can use https://cards-dev.twitter.com/validator to test in the meantime.
