### ISSUE TITLE
Level 9 - Bass in Uptown Funk not low enough to be detected.

### ISSUE THREAD

**Issue by jmkulwik** [code-dot-org/dance-party#281]
Uptown Funk singing is detected as "mid" instead of "bass." Try using one of these songs as the default instead. Or change "bass" to "mid"

will.i.am - I Like to Move it
Sia - Cheap Thrills
Imagine Dragons - Thunder

**Comment by ryansloan** [comment]
This is because the singer's voice is in the "mid" bucket of frequencies - it will depend on what the singer's pitch is and how it compares to the instruments used in the song.
