### ISSUE TITLE
conflicting pop-ups: show age dialog before showing tutorial video

### ISSUE THREAD

**Issue by tanyaparker** [code-dot-org/dance-party#283]
If I'm a signed out user and I visit the first level of dance party, I see the intro video pop up first. Once I exit that, I have to select my age. You should see the age dialog pop up before the video. This should apply to all levels with a video, even though they're unlikely to start in the middle of the tutorial.

**Comment by boatmarina** [comment]
I think i heard @ryansloan say this isn't totally straightforward to fix and given how many bugs we still have left to fix, I'm OK with the experience as is.  marking as won't fix
