### ISSUE TITLE
Some song titles have incorrect capitalization

### ISSUE THREAD

**Issue by jmkulwik** [code-dot-org/dance-party#286]
I Like to Move it -> I Like To Move It
Born this Way -> Born This Way
Take on Me -> Take On Me

**Comment by ryansloan** [comment]
I'll check w/ our consultant, these were the capitalizations we were given.

**Comment by breville** [comment]
fwiw, iTunes shows:

will.i.am: I Like to Move It (vs. Spotify: I Like To Move It)
Lady Gaga: Born This Way
a-ha: Take On Me

**Comment by ryansloan** [comment]
I updated these in the manifest
