### ISSUE TITLE
No certificate available for the second stage of dance party

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#292]
can we hook up the generic HOC congrats page for the dance-extras tutorial (so that there's a "I finished!" link at the end of it and you can get a certificate).  should be the generic version, not the dance party version.

![image](https://user-images.githubusercontent.com/33850843/48377775-8ae27000-e683-11e8-8245-869dbe4cc4ed.png)

**Comment by Erin007** [comment]
https://github.com/code-dot-org/code-dot-org/pull/26065, will also need a content scoop of pegasus/data/cdo-tutorials.csv
