### ISSUE TITLE
Update preload asset lists with new spritesheet urls

### ISSUE THREAD

**Issue by islemaster** [code-dot-org/dance-party#293]
As some of the work for https://github.com/code-dot-org/dance-party/issues/233 we started packing multiple animations into a single spritesheet, which changed the URLs of all of our spritesheet assets.  However, the preload asset lists of the levels are all pointing to the old assets, which means we're actually downloading extra assets now that we aren't using.

We need to go through the level files and update the preload asset list asset names.

Here's an example preload asset list:

https://github.com/code-dot-org/code-dot-org/blob/b7ab9387256e99f4a83c4727e51f5a6f9a2e5dc2/dashboard/config/scripts/levels/Dance_Party_01.level#L40-L56

The new assets are at `/images/sprites/dance_grouped/` and here's the list:
```
alien_00.png
alien_01.png
alien_02.png
alien_03.png
bear_04.png
bear_05.png
bear_06.png
bear_07.png
cat_08.png
cat_09.png
cat_10.png
cat_11.png
dog_12.png
dog_13.png
dog_14.png
dog_15.png
duck_16.png
duck_17.png
duck_18.png
duck_19.png
frog_20.png
frog_21.png
frog_22.png
frog_23.png
moose_24.png
moose_25.png
moose_26.png
moose_27.png
pineapple_28.png
pineapple_29.png
pineapple_30.png
pineapple_31.png
robot_32.png
robot_33.png
robot_34.png
robot_35.png
shark_36.png
shark_37.png
shark_38.png
shark_39.png
unicorn_40.png
unicorn_41.png
unicorn_42.png
unicorn_43.png
```

**Comment by islemaster** [comment]
It would be nice to add https://curriculum.code.org/images/DancePartyLoading.gif to the top of the preload asset list for all of the dance party levels too - just to make sure the loader is ready to show as soon as the page render is done.

**Comment by islemaster** [comment]
Also, a bug: We're seeing `GET https://curriculum.code.org/media/uploads/touch.mp3 net::ERR_ABORTED 404 (Not Found)` on s/dance/stage/1/puzzle/1 which is in the preload list for the level and should be removed.

**Comment by ryansloan** [comment]
I have updated all these on levelbuilder.
