### ISSUE TITLE
Start button on /congrats page should take you to first level

### ISSUE THREAD

**Issue by poorvasingal** [code-dot-org/dance-party#295]
![image](https://user-images.githubusercontent.com/16227893/48377997-4c00ea00-e684-11e8-9e39-2febb42dd66c.png)

^ That should go to the first level. So link to this instead: https://studio.code.org/s/dance-extras/reset

CC @Erin007

**Comment by Erin007** [comment]
Will be updated/fixed with https://github.com/code-dot-org/code-dot-org/pull/25754
