### ISSUE TITLE
I can't customize the certificate on /congrats page

### ISSUE THREAD

**Issue by poorvasingal** [code-dot-org/dance-party#296]
I'm not seeing an option to customize / add my name on staging-studio.code/congrats

![image](https://user-images.githubusercontent.com/16227893/48378208-fd078480-e684-11e8-859d-3b2b89f9dfe6.png)

**Comment by ryansloan** [comment]
@poorvasingal which tutorial is this for? dance or dance-extras?

**Comment by poorvasingal** [comment]
I think it was just the regular congrats page.

**Comment by breville** [comment]
This should work for danceparty going through the full flow.  

I just saw it working by visiting https://staging.code.org/api/hour/begin/dance (which is what /dance should point at) to set the cookie, then going to https://staging-studio.code.org/s/dance/stage/1/puzzle/13 and pressing "I finished", which went to a https://staging-studio.code.org/congrats?i=ID URL with the ID from the cookie, and then the certificate was customisable.

**Comment by ryansloan** [comment]
This is by design on the /congrats page.
