### ISSUE TITLE
Tacos foreground effect looks glitchy

### ISSUE THREAD

**Issue by poorvasingal** [code-dot-org/dance-party#305]
![tacosgif](https://user-images.githubusercontent.com/16227893/48382935-76f53900-e698-11e8-9e1d-aae838f61d00.gif)

This is on Chrome, MacOS

**Comment by boatmarina** [comment]
@poorvasingal does this still repro for you?  can you see if this repro's for other people so we can figure out if we need to fix this or can won't fix it?

**Comment by ryansloan** [comment]
I repro as well. I think we should include this in #215

**Comment by boatmarina** [comment]
@simplycloud i'm hoping this goes away once we update the foregrounds to be images rather than emoji's?  not sure what is causing this, so assigning this to you in case this is a problem for other foregrounds as you're working on this.

**Comment by simplycloud** [comment]
resolved by moving to SVGs. no longer glitchy!
