### ISSUE TITLE
Level 2: video shows event firing at wrong time

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#312]
The video shows the new dance move starting at measure 4, not measure 5, despite just explaining that it begins after 4 bars have finished.

**Comment by breville** [comment]
It's pretty clearly wrong:

![screenshot 2018-11-14 06 19 53](https://user-images.githubusercontent.com/2205926/48437379-4f57bb00-e7d5-11e8-8e35-ce817786ac38.png)

**Comment by ryansloan** [comment]
Jael is working on recutting this

**Comment by breville** [comment]
@ryansloan Great.  Will the recut include hiding "Measure: 0", and only showing 1 onwards, which is coming in a [PR](https://github.com/code-dot-org/dance-party/pull/270) shortly?

**Comment by breville** [comment]
cc @tanyaparker in case this impacts the video notes & screenshots.

**Comment by tanyaparker** [comment]
https://github.com/code-dot-org/code-dot-org/pull/26032/commits/61b908f058be57e6e91bf6e0f58d9410e522a0a8

Updated the pic in show notes from 4 measures to 5 measures.

**Comment by ryansloan** [comment]
This will be fixed in the deploy today
