### ISSUE TITLE
Levels finish one bar too early

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#313]
The hint in level 2 says it finishes after 8 measures, but it finishes after 7.

It does feels too abrupt, too.

**Comment by breville** [comment]
It appears that other levels have this off-by-1 issue too.

**Comment by ryansloan** [comment]
@mrjoshida updated these on levelbuilder today.

**Comment by boatmarina** [comment]
darn, i do agree that this sounds better at the end of 8, but updating these strings now will invalidate translations, so won't fix'ing.

**Comment by breville** [comment]
:(
