### ISSUE TITLE
Blocks overlap when doing things properly

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#316]
It's still easy to end up with overlapping blocks even when doing things properly.

This is what happens when dragging one block into the "setup" jaws in level 4:

![screenshot 2018-11-13 13 39 47](https://user-images.githubusercontent.com/2205926/48387392-b891ec80-e749-11e8-8051-5d10a5f26138.png)

**Comment by breville** [comment]
This is noticeably painful on level 7 when following the technique shown in the video.

**Comment by breville** [comment]
We solved this in starwars by specifying coordinates for existing blocks.  e.g. https://github.com/code-dot-org/code-dot-org/blob/staging-next/apps/src/studio/levels.js#L3375

In the above screenshot it means we'd provide coordinates for the green event block to make sure there is extra room above it.

**Comment by ryansloan** [comment]
I've updated y coordinates for all puzzles that needed them on levelbuilder.
