### ISSUE TITLE
Level 5: hint is not helpful

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#317]
The hint says "Your dance must perform different moves throughout the first 12 measures of the song."

Suggestion is to be more specific, especially given we're introducing a new block here which we never specify, even in hints:

hint 1: "Use the new 'every 2 measures' block to change dance move every two measures.
hint 2: "Place a 'do forever' block inside your 'every 2 measures block' to change to a new dance every two measures.

**Comment by ryansloan** [comment]
@mrjoshida We're going to cut this hint - the requirements are stated in the instructions.

**Comment by mrjoshida** [comment]
Removed
