### ISSUE TITLE
Can play same song twice at same time

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#322]
While reproing https://github.com/code-dot-org/dance-party/issues/321, I was able to reset but the song was still playing, and I could press run again and now the same song was playing twice.

I have a video that I can share.

**Comment by breville** [comment]
Video: https://www.dropbox.com/s/8izklvjyg0iyc6t/IMG_7368.MOV?dl=0

**Comment by ryansloan** [comment]
@breville Have you been able to do this in any way other than crashing your app w/ the "every" block?

**Comment by poorvasingal** [comment]
It seems like if you're in this situation, other things are bad enough that you'd end up needing to close your tab, right? Which makes me lean towards not trying to fix this before HOC (just given how high the bar seems to be getting right now for bugs). I am also not able to repro in other ways (e.g. using a block that gives me a JS error). 

CC @boatmarina

**Comment by boatmarina** [comment]
hmmm, not sure if this is something we should investigate further.  I don't think anyone has bandwidth to look at this and since no one else has reported it, i'm leaning to won't fix'ing this.  @ryansloan @simplycloud @breville if you disagree
