### ISSUE TITLE
Level 7: super nit on pluralisation

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#324]
I couldn't be more nitty, but 

"Every dancer has a set of properties that control what it looks like." 

should possibly be

"Every dancer has a set of properties that controls what it looks like." 

Because we are talking about a singular set :)

**Comment by ryansloan** [comment]
Grammatical correctness appreciated, but @mrjoshida decided to go with common english usage because the right way sounds wrong-er.
