### ISSUE TITLE
Level 11: block text in hint is inconsistent and not quite right

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#325]
In level 4, a block has a proper appearance:

![screenshot 2018-11-13 14 33 09](https://user-images.githubusercontent.com/2205926/48389325-170e9900-e751-11e8-9687-114abbcfe110.png)

But in level 11 it has this:

![screenshot 2018-11-13 14 31 13](https://user-images.githubusercontent.com/2205926/48389282-dd3d9280-e750-11e8-9635-cbb8df613f4d.png)

Suggestion 1: show block image instead of text.
Suggestion 2: if nothing else, remove the word "pressed" from this text.

**Comment by boatmarina** [comment]
related to #259 

if this doesn't affect translation, i think we can live with this.

**Comment by boatmarina** [comment]
this doesn't affect translations, so marking as won't fix
