### ISSUE TITLE
Dancers don't render in back-to-front order

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#327]
Dancers are not drawn in what appears to be a back-to-front order.

![screenshot 2018-11-13 14 48 09](https://user-images.githubusercontent.com/2205926/48389825-3d353880-e753-11e8-84b3-37ddfb050393.png)

Did we not implement paint order by Y coordinate?

**Comment by joshlory** [comment]
Related issue, with slightly different requirements: https://github.com/code-dot-org/dance-party/issues/154.

**Comment by ryansloan** [comment]
Making #154 more general and duping to that.
