### ISSUE TITLE
Puzzle 9: shark doesn't appear to respond to bass

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#328]
The first thing to do is run the existing program to observe the shark responding to the bass, to understand what's being taught.

The shark does not appear to be responding to the bass.  It stays basically squashed the same amount for the whole snippet that you can see.

**Comment by boatmarina** [comment]
looking at level 9 right now, seems like this is working as expected.  @breville can you check to see if what you were seeing before is no longer repro'ing please?

(note, looks like the default block got changed to follow treble instead of bass in this level now)

**Comment by breville** [comment]
@boatmarina I just tried https://test-studio.code.org/s/dance/stage/1/puzzle/9 with shark following treble, and unicorn following bass (which is still the instructions).

Honestly, they do wobble in size a tiny bit, but neither character's size really seems to have any relationship to the music.

I would say there's still an issue here.

**Comment by breville** [comment]
I tried again with https://test-studio.code.org/s/dance/stage/1/puzzle/9  and it seems the song has changed again to Keith Urban.

The left shark continues to wobble around a bit but I don't think it's working well enough to see that it's "following" the treble.

If it were really following what the user hears as treble, it would be bopping along to the twanging from the very beginning.

In fact, the shark behaves almost identically whether following bass, mid, or treble.

Here's a video:

https://www.dropbox.com/s/pty8hnawtyqa6ji/IMG_7413.MOV?dl=0

**Comment by boatmarina** [comment]
we have another bug tracking updates to how the following block works.  that may change what this experience looks like:  #75

**Comment by ryansloan** [comment]
We have another change of this block's behavior in progress that intensifies the movement during "typical" periods of the song, and also makes them relative to the sprite's initial properties. This looks a lot more dynamic than the current behavior (in which local maxima get deemphasized due to global minimum of 0) Duping this to that tracking issue #75
