### ISSUE TITLE
Document the need to run `nvm use` in README.md

### ISSUE THREAD

**Issue by joshlory** [code-dot-org/dance-party#33]
Add steps for cloning and setting up the playground locally.  The [Craft README.md](https://github.com/code-dot-org/craft/blob/master/README.md) has a good example.

I think they're just the following, but we should verify:

```
git clone git@github.com:code-dot-org/dance-party.git
cd dance-party
nvm use
npm install
npm run dev
```

**Comment by joshlory** [comment]
+cc @islemaster

**Comment by Bjvanminnen** [comment]
resolved by https://github.com/code-dot-org/dance-party/pull/70
