### ISSUE TITLE
 doMoveEachLR and changeMoveEachLR clear on "(random)" if the group is empty

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#335]
Repro:
<img width="637" alt="screen shot 2018-11-12 at 7 47 39 pm" src="https://user-images.githubusercontent.com/1669271/48390367-74a1d780-e6b6-11e8-91ab-465731c00a69.png">

Observed: display area freezes
Expected: this is a no-op as long as there are no bears.

The issue appears to be that we index into an empty group and try to read a property in two places:
https://github.com/code-dot-org/dance-party/blob/master/src/p5.dance.js#L501

https://github.com/code-dot-org/dance-party/blob/master/src/p5.dance.js#L511

**Comment by joshlory** [comment]
Regressed in PR https://github.com/code-dot-org/dance-party/pull/299.
