### ISSUE TITLE
Loading animation looks like a glitch when things are cached

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#338]
When things are already cached, the new loading animation flickers on for a frame or so and vanishes, feeling like a glitch.  

It's good practice for such animations to maybe have a delay before initially showing in case they aren't needed, and regardless a minimum display time so that if they do get shown, they show for long enough for the user to understand what they are.

**Comment by islemaster** [comment]
:+1: Thanks for suggesting best practices here! I'd never thought about this much, that makes a lot of sense.
