### ISSUE TITLE
Opinion: simplify loading graphic

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#339]
The loading graphic seems to have both silhouettes and they're dancing on top of a tiny spinning disc which might be vinyl?

Simply my opinion: simplify and just use the silhouettes.

We don't use vinyl anywhere else for this tutorial, it's too small to read read properly, and it makes things busy by having the dancers kind of dancing on top of it.

**Comment by boatmarina** [comment]
good feedback.  but i think at this point, we should leave it as is.  we added the spinning UI because we were worried people might think that the animating characters are the actual thing rather than a progress UI.
