### ISSUE TITLE
No more / less buttons in dance-extras instructions

### ISSUE THREAD

**Issue by poorvasingal** [code-dot-org/dance-party#345]
Probably not a huge deal but maybe just a matter of a flag to fix it? Some of the instructions get long in dance-extras so I was surprised to see that the instructions didn't scroll or show the more / less buttons. 

![image](https://user-images.githubusercontent.com/16227893/48393033-be90ba80-e6c2-11e8-9ffa-fb11a0fe6626.png)

**Comment by ryansloan** [comment]
This is because we have no short instructions. I added them to the following levels:

Dance_Party_extras_layout
Dance_Party_extras_visible
Dance_Party_extras_battle
Dance_Party_extras_every_beat
Dance_Party_extras_on_beat
Dance_Party_extras_speed
