### ISSUE TITLE
Instruction arrows get cut off when trying to resize instructions

### ISSUE THREAD

**Issue by poorvasingal** [code-dot-org/dance-party#346]
The scrolling arrows get clipped off on the right edge:
![image](https://user-images.githubusercontent.com/16227893/48393460-89856780-e6c4-11e8-89d7-ee17f666ffe3.png)

**Comment by ryansloan** [comment]
@poorvasingal This should be a dupe of #345 - can you check to see if this still repros on this level on levelbuilder? You can reopen if it still repros on levelbuilder.
