### ISSUE TITLE
Pineapple - switch outfit

### ISSUE THREAD

**Issue by alicesteinglass** [code-dot-org/dance-party#350]
Switch to the new Pineapple outfit.

**Comment by ryansloan** [comment]
Where are you seeing the old one? I am seeing the new Pineapple on production:

<img width="417" alt="screen shot 2018-11-12 at 10 29 17 pm" src="https://user-images.githubusercontent.com/1669271/48394975-6c539780-e6ca-11e8-8d9a-536f05264d34.png">
