### ISSUE TITLE
Lesson plan bugs

### ISSUE THREAD

**Issue by alicesteinglass** [code-dot-org/dance-party#352]
We renamed the dance moves, so we need to update the deck here: https://docs.google.com/presentation/d/1Guau5AeuqQCcPz06bfhtTmgt_ykaxKZ_JzkhzcECOcQ/edit#slide=id.g441e51501a_0_15

And the corresponding names in the lesson plan

**Comment by ryansloan** [comment]
@mrjoshida or @mikeharv can you own?

**Comment by mrjoshida** [comment]
updated
