### ISSUE TITLE
I can delete the only "make a dancer" block on puzzle 4

### ISSUE THREAD

**Issue by islemaster** [code-dot-org/dance-party#356]
Not actually required to pass the level, but not great that we can delete this but not get it back.

**Comment by islemaster** [comment]
Same with level 5, and this time it might be required to pass the level?

**Comment by ryansloan** [comment]
@mrjoshida will add to toolbox

**Comment by mrjoshida** [comment]
Added to toolbox in levels 2-5 so that you can always recreate starter code
