### ISSUE TITLE
Level 1 & 2 are using the same song. 

### ISSUE THREAD

**Issue by alicesteinglass** [code-dot-org/dance-party#357]
We should change one so every level is different.

**Comment by alicesteinglass** [comment]
Actually, 9& 4 also use the same song (uptown funk)

And, while we're at it, can we switch level 12 to something else... the level is only 8 measures long so it cuts out before the "move it, move it" part. Maybe Ciara?

**Comment by boatmarina** [comment]
Let's do another pass through on the songs that we're using, to make sure we have a mix of song styles but that they also work well with each of the levels.

**Comment by ryansloan** [comment]
I'll swap in some new ones, I'll talk to Alice.

**Comment by ryansloan** [comment]
Ok, here's the new list, in order.

1) canttouchthis_mchammer
2) firework_katyperry
3) callmemaybe_carlyraejepsen
4) sorry_justinbieber
5) notearslefttocry_arianagrande
6) somebodylikeyou_keithurban
7) backtoyou_selenagomez
8) bornthisway_ladygaga
9) summer_calvinharris
10) wakemeup_aviciialoeblacc
11) takeonme_aha
12) levelup_ciara
13) cheapthrills_sia


@alicesteinglass lmk what you think. won't go out tonight but will go out with the next deploy.

**Comment by alicesteinglass** [comment]
I'm checking with Josh S. he is going to let us know which are the most popular songs so we can include those. (while also balancing some old classics and diversity of music and what works well in the actual activity)

**Comment by ryansloan** [comment]
Ok, we should just keep in mind that we can only use songs that are all ages for these.

**Comment by alicesteinglass** [comment]
Ok... spent time looking at their following on spotify, spotify popularity, asks for promotions in marketing, etc. and here's the list we want to use in this order: 

Madonna
firework_katyperry
J Balvin
bornthisway_ladygaga
Uptown funk
notearslefttocry_arianagrande
sorry_justinbieber
backtoyou_selenagomez
somebodylikeyou_keithurban
summer_calvinharris
callmemaybe_carlyraejepsen
Outkast
cheapthrills_sia

@ryansloan

**Comment by alicesteinglass** [comment]
If there is an issue with using any of these let me know.

**Comment by ryansloan** [comment]
these are updated on levelbuilder
