### ISSUE TITLE
No feedback or hint when applying a property to a dancer that doesn't exist

### ISSUE THREAD

**Issue by islemaster** [code-dot-org/dance-party#359]
Level 7: It's not very clear why this doesn't work, especially since most of the code so far has been more-or-less declarative.

![image](https://user-images.githubusercontent.com/1615761/48397143-ad9b7580-e6d1-11e8-901e-161c640b3a8b.png)

**Comment by ryansloan** [comment]
We try to address this in the video. @mrjoshida as we monitor feedback, we should keep an eye out for anything in particular we can do here

**Comment by ryansloan** [comment]
We would have to handle in library code, we're not going to do this for HOC.
