### ISSUE TITLE
Level 9: Hard to play at small resolutions

### ISSUE THREAD

**Issue by islemaster** [code-dot-org/dance-party#361]
![image](https://user-images.githubusercontent.com/1615761/48397391-5944c580-e6d2-11e8-9c1b-2e932a38001e.png)

This is 1024x768.

The very wide toolbox and the fact that you can't scroll the blockspace horizontally makes it really painful to interact with, say, the third parameter of the `<dancer> begins <property> following <cue>` block.

Do we need to line-wrap some of these blocks like the make a new dancer block?

**Comment by joshlory** [comment]
Duplicate of issue https://github.com/code-dot-org/dance-party/issues/210?

**Comment by islemaster** [comment]
Yep, closing in favor of #210.
