### ISSUE TITLE
Respect flag to hide Dance extras on /congrats

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#364]
Use the same flag as @nkiruka 's /dance page

**Comment by Erin007** [comment]
https://github.com/code-dot-org/code-dot-org/pull/26052

**Comment by boatmarina** [comment]
i think the traffic to dance extras from this page is going to be very very small so not sure it's necessary to do this

**Comment by Erin007** [comment]
Is it a "nice to have" since the work is already finished or would you like me to close the PR @boatmarina?

**Comment by mrjoshida** [comment]
Probably not a representative sample, but worth noting that I'm seeing lots of the twitter shared projects using blocks that are only available in dance-extras, so it's getting some use early on.

**Comment by Erin007** [comment]
merged! Better to have it and not need it than need it and not have it.
