### ISSUE TITLE
Style nits to tutorial hero on /dance

### ISSUE THREAD

**Issue by tanyaparker** [code-dot-org/dance-party#365]
![image](https://user-images.githubusercontent.com/1920530/48449710-57bde080-e758-11e8-8d99-21515ff68858.png)

1. Artist names grew so now Featuring overlaps with the Dance Party tile. We should be flexible to possibly receive 3 more names.

2. The hero banner image isn't large enough so there is a small banner of black at the bottom. We should determine what size we need and ask Mark for a new image with those dimensions.

**Comment by nkiruka** [comment]
[PR #26075](https://github.com/code-dot-org/code-dot-org/pull/26075)

**Comment by joshlory** [comment]
Verified fix on https://code.org/dance.
