### ISSUE TITLE
Closing finish dialog takes me to /congrats

### ISSUE THREAD

**Issue by madelynkasula** [code-dot-org/dance-party#366]
Closing the "finish" dialog (via the X in the corner of the dialog) in puzzle 13 takes me to /congrats -- I would expect it to keep me on the puzzle (as the "replay" button in the dialog currently does).

![close-dialog](https://user-images.githubusercontent.com/9812299/48449761-8340cb00-e758-11e8-9a0a-76e17a327eeb.gif)

**Comment by boatmarina** [comment]
@ryansloan  ah yes, this is a long-standing discussion of whether hitting x should keep you in the level or progress you further.  in all of our courses, the x does move you forward so i think it makes sense to stick with the consistency at the very last level of the tutorials.  though i totally get that some people would expect you to keep in the level (I have the same instinct.)  I think this is a design decision we'd have to make about this on the whole (not just for this tutorial) so marking as won't fix for dance party.
