### ISSUE TITLE
IE 11 & Edge - downloading a video from tutorial broken

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#372]
works fine in Chrome but broken in Edge and in IE 11.  Downloading a tutorial video loads this page:

![image](https://user-images.githubusercontent.com/33850843/48458966-5652df00-e77d-11e8-892f-534ebcde1499.png)

**Comment by breville** [comment]
@tanyaparker Do these have "Content-Disposition" of "attachment" in S3?

**Comment by tanyaparker** [comment]
No, it doesn't. I tried setting it in aws but it's giving me an error that the string is empty when it's not.
![image](https://user-images.githubusercontent.com/1920530/48492102-e58fdf00-e7dd-11e8-93d9-5897069ad73a.png)

But, I'm able to download the video from the tutorial fine on chrome.

**Comment by boatmarina** [comment]
Works now!  closing.
