### ISSUE TITLE
Some shared projects play Katy Perry even though another song was chosen

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#375]
Share project to phone, and on the phone, Firework plays even though I've picked other songs.  I've done this multiple times now, opening up private browser sessions each time.  This looks to repro whenever we're also unable to generate a thumbnail for the project.  (Also - may or may not be related - no twitter handles show up when sharing to twitter).  

The more i've played with this, the less likely IE is able to generate a thumbnail.  I'm now at a point that i can't get any thumbnails to generate whatsoever, even though i've played with each project for over a minute (while signed out and incognito mode every time.)  have not ever repro'ed this in chrome.

**Comment by boatmarina** [comment]
The videos in the tutorials are also taking about 12 seconds  to load (to go from white screen to black) so certainly feels like there's some perf thing going on with my machine right now. that said, lots of kids will have slow machines/connections so doing some work to make sure the right song actually ends up getting shared when internet is slow would be good

**Comment by boatmarina** [comment]
note, twitter handles being missing does NOT look to be related.  even when i do get a thumbnail generated (and the right song to play in the shared version), the twitter artist handle still doesn't populate in IE.  logging a separate issue for the twitter handle not working in IE (#376)

**Comment by boatmarina** [comment]
in case this is helpful, look at how my machine is doing right now (note the memory utilization):
![image](https://user-images.githubusercontent.com/33850843/48461704-ce270680-e789-11e8-861b-c1dbff6fe459.png)

**Comment by simplycloud** [comment]
I was able to replicate this on MacOS and Safari. I have a share URL that can be used to investigate.

**Comment by ryansloan** [comment]
Thanks Dave, I opened #388
