### ISSUE TITLE
IE:  Twitter handles not loading

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#376]
twitter artist handles don't seem to ever load for any of the songs/artists in IE.

**Comment by boatmarina** [comment]
If this is just in IE 11, we should probably won't fix this bug at this point.  just want to make sure we verify that this is just IE 11 before I close this down.

**Comment by Erin007** [comment]
@boatmarina can you let me know when you've determined whether this is something I should focus on or not?  Thanks!

**Comment by boatmarina** [comment]
Marking this as won't fix.  @simplycloud FYI
