### ISSUE TITLE
Epilepsy risk?

### ISSUE THREAD

**Issue by islemaster** [code-dot-org/dance-party#378]
The flashing spiral effect at the [beginning of this dance](https://studio.code.org/projects/dance/ZZ3CKXXmUdLrih9cfWbwmw) featured on `/dance` worries me a bit:

![peek 2018-11-13 22-49](https://user-images.githubusercontent.com/1615761/48465171-c9b51a80-e796-11e8-9bcf-0f277a70d37d.gif)

From [StackExchange](https://gamedev.stackexchange.com/a/9075):

> A group that studied the Pokemon epilepsy phenomenon came up with the following recommendations:
> 
> - Flashing images, especially those with red, should not flicker faster than three times per second. If the image does not have red, it still should not flicker faster than five times per second.
> - Flashing images should not be displayed for a total duration of more than two seconds.
> - Stripes, whirls and concentric circles should not take up a large part of the television screen.

We've got fairly rapid flashing of bright and dark colors, with red and blue back-to-back, in a swirl.  It may reduce the risk that we're not taking up a large portion of the screen, but it might be worth investigating.

[University of Maryland has a free analysis tool](https://trace.umd.edu/peat#sysreqs) but it's not Linux-friendly; can someone on windows try this out?

**Comment by islemaster** [comment]
@epeach Do you know of any tools for testing this sort of thing?

**Comment by simplycloud** [comment]
We can either find a tool that tests and validates that this background is safe, or we can slow down the color change...

**Comment by epeach** [comment]
Update: I ran 60 seconds of our spiral through the PEAT tool. The tool did not indicate any warnings and the video rarely and barely registered in the 'Caution (Pass)' field. Based on that metric, the spiral background would not cause seizures. 

The WCAG advises no more than 3 flashes per second (https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure.html) and it looks as if the effect only updates the color when isPeak and the spiral speed is determined by bpm. Someone with more music knowledge than I might be able to let us know if we are at risk of having 3 or more isPeak within one second. If that is possible, we could throttle the isPeak for this effect to avoid changing the color more than 3 times per second.

I did not discover a tool, measure, or guideline for the risk associate with the 'swirl/spiral', other than that it (and similar patterns) could cause seizures (http://epilepsytoronto.org/wp-content/uploads/2015/09/EFS-Photosensitive1.pdf), especially when they are not stationary.

Based on these results, I believe the only action here is to confirm that isPeak cannot happen more than 3 times per second and then decide whether having the spinning swirl is a tolerable risk.

**Comment by islemaster** [comment]
The highest tempo in our current selection of songs is is 169bpm (2.8 beats per second).  If peak frames happen more often than beats (and it sounds like they _can_ but we'd need to spot check our generated metadata to see if this happens) then we'd be able to exceed the 3hz threshold.

**Comment by islemaster** [comment]
That said I feel a lot better having _some_ tool output saying this is okay.

**Comment by simplycloud** [comment]
@epeach thanks for the find and testing this! we can have you move on to other items for CSED week. i'm going to leave this open until i confirm that we don't need any changes to reduce the likelihood of  the 3 isPeak per second concern.

**Comment by boatmarina** [comment]
@epeach talking through this with @simplycloud today, we thought one more good test might be to use a song that has the highest BPM in our list and run the tool with the spiral effect background going to that song (this seems to be the worst possible case for this.)  If you think of other 'worst cases' to try out, please try to do that as well and if the tool passes, let's close this out!

**Comment by epeach** [comment]
With @jmkulwik , we tested the hypno effect with 'Aha - Take On Me' (bpm 169), using the warm, tropical, and neon palettes. We also tested the spiral effect with 'Aha - Take on Me' using the warm palette. The PEAT tool did not indicate an epilepsy warning on any of these backgrounds. Based on these outcomes, I believe we can close this issue.
