### ISSUE TITLE
Polish: positioning of measure text

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#379]
Would it be good to make the M equidistant from the top and the left edges?

<img width="45" alt="screen shot 2018-11-14 at 11 13 31 pm" src="https://user-images.githubusercontent.com/2205926/48481856-0bab9280-e863-11e8-8481-640d125cd3c5.png">

**Comment by boatmarina** [comment]
I also want to update the visual of the measure counter (font color and perhaps transparent bar behind it).  mark has a design for it, but i want @ryansloan to look at it before we do anything with this

**Comment by boatmarina** [comment]
This one makes me sad, but I think we need to push this out after HOC

**Comment by breville** [comment]
@boatmarina For what it's worth, it's just a few lines of code to make changes to this.  Here are some late-night quick prototypes done in code:

![screenshot 2018-11-21 23 57 39](https://user-images.githubusercontent.com/2205926/48843377-f72f4300-edea-11e8-8e00-8b73e0a75fc2.png)
![screenshot 2018-11-21 23 58 05](https://user-images.githubusercontent.com/2205926/48843379-f7c7d980-edea-11e8-9c26-ba63bb026670.png)
![screenshot 2018-11-22 00 04 04](https://user-images.githubusercontent.com/2205926/48843387-fc8c8d80-edea-11e8-9013-f952f6897422.png)
![screenshot 2018-11-22 00 08 10](https://user-images.githubusercontent.com/2205926/48843388-fc8c8d80-edea-11e8-982f-9199967dc10c.png)
![screenshot 2018-11-22 00 08 53](https://user-images.githubusercontent.com/2205926/48843389-fd252400-edea-11e8-99aa-3c0affe68b2b.png)

**Comment by breville** [comment]
By using a light background rectangle we can make the text legible over both light and dark backgrounds:

![screenshot 2018-11-24 14 54 09](https://user-images.githubusercontent.com/2205926/48964388-43040700-effa-11e8-867f-464d779dfd33.png)
![screenshot 2018-11-24 14 54 21](https://user-images.githubusercontent.com/2205926/48964389-439c9d80-effa-11e8-8905-64a2ae19dde7.png)

I have this working in code now, with dynamic width based on the text.

**Comment by simplycloud** [comment]
I think we need to do this work because the Measure text may be hidden on some of our backgrounds if we do not.

**Comment by boatmarina** [comment]
@breville did you mean to close this?  don't think it's merged yet, right?

**Comment by breville** [comment]
@boatmarina I merged it late yesterday with approval.  It should be in today's build.
