### ISSUE TITLE
Section assignment dropdown updates for Dance

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#381]
They are set to "visible" on Levelbuilder, but we need two other changes:

- [x] Move Dance Party to the top of the dropdown
- [x] Add "Keep On Dancing" to the "Hour of Code" category (it is in Other)

<img width="330" alt="screen shot 2018-11-14 at 8 37 17 am" src="https://user-images.githubusercontent.com/1669271/48497217-90a59600-e7e8-11e8-8562-b85de520bb75.png">

**Comment by davidsbailey** [comment]
@ryansloan , my pending fix has `Dance Party` and `Keep on Dancing` as the first two entries under Hour of Code. Please let me know if this doesn't look right:
<img width="362" alt="screen shot 2018-11-14 at 3 09 34 pm" src="https://user-images.githubusercontent.com/8001765/48518757-6f13d100-e81f-11e8-8bbc-17001a8b479b.png">
