### ISSUE TITLE
Default volume is too loud

### ISSUE THREAD

**Issue by joshlory** [code-dot-org/dance-party#383]
Compared to all other sounds on my laptop, Dance Party seems to always run at 100% volume 😂.

**Comment by joshlory** [comment]
![image](https://user-images.githubusercontent.com/413693/48570885-3ecd4080-e8ba-11e8-82af-6c4440544c6f.png)

**Comment by boatmarina** [comment]
I'm OK won't fix'ing this given how many other issues we have right now to fix still. marking as won't fix.
