### ISSUE TITLE
Enable project save on share and finish

### ISSUE THREAD

**Issue by simplycloud** [code-dot-org/dance-party#384]
Currently, when a dance party project is created on level13, we save the student code on each Run. However, in a scenario where a student makes a change to the code post-run and then clicks Finish or Share we do not save the latest changes. We'd like to enable project save on Run, Finish, and Share.

**Comment by islemaster** [comment]
@simplycloud I don't repro this for the Share button - I _am_ seeing a save event following these steps:

1. While _not_ signed in,
1. When I visit `/s/dance/stage/1/puzzle/13`
1. And I click run
1. Then main.json is saved.
1. When I click reset
1. And I make a code change
1. And I click "Share"
1. Then main.json is saved
