### ISSUE TITLE
(low pri) Style nit to listing artist names

### ISSUE THREAD

**Issue by tanyaparker** [code-dot-org/dance-party#386]
Either center justify or add separators between each name. I have a preference for the latter.

![image](https://user-images.githubusercontent.com/1920530/48512139-9a8dc000-e80d-11e8-9022-43dee17aa657.png)

**Comment by boatmarina** [comment]
scrubbing through bug list, we still have quite a lot of bugs left.  I think we can live with the way it currently is. marking as won't fix
