### ISSUE TITLE
Thumbnail Generation is flaky

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#388]
> The more i've played with this, the less likely IE is able to generate a thumbnail. I'm now at a point that i can't get any thumbnails to generate whatsoever, even though i've played with each project for over a minute (while signed out and incognito mode every time.) have not ever repro'ed this in chrome.

Broken out from #375

**Comment by ryansloan** [comment]
This is not just IE, this is across the board

**Comment by boatmarina** [comment]
Assuming this is not happening a lot, let's just use the generic image for Dance Party here in the cases where a thumbnail is not generating (instead of the teal arrow icon.)

**Comment by islemaster** [comment]
Double-check this after today's DTP: Possible this will be improved by https://github.com/code-dot-org/code-dot-org/pull/26100 if the problem is that we're generating thumbnails but not uploading them because we're missing a save.

**Comment by islemaster** [comment]
Related to https://github.com/code-dot-org/dance-party/issues/261

**Comment by islemaster** [comment]
Probably addressed by https://github.com/code-dot-org/code-dot-org/pull/26151? @madelynkasula let me know what you think.

**Comment by madelynkasula** [comment]
@islemaster yep, my PR will fix that. i hadn't realized this was a logged issue or i would've let folks know sooner!

**Comment by madelynkasula** [comment]
Fixed by [code-dot-org#26151](https://github.com/code-dot-org/code-dot-org/pull/26151)
