### ISSUE TITLE
Music playing twice simultaneously

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#39]
Haven't worked out a repro, but in a quick bit of testing I managed to have the same song playing twice simultaneously with just a tiny delay.

**Comment by ryansloan** [comment]
Ah, I have a repro. Double-click "Run". The music continues playing even though it should've reset

**Comment by breville** [comment]
Does this mean we might have a resource leak (at the WebAudio level) when playing songs?  I'd have thought that playing a song a second time would tear down the current resources first.

**Comment by breville** [comment]
To answer my previous question, probably yes: https://github.com/code-dot-org/dance-party/issues/56

**Comment by Bjvanminnen** [comment]
+1 FWIW I also just repro'd this unintentionally by clicking reset shortly after clicking run

**Comment by ryansloan** [comment]
@brendan, can you try reproing this again on staging? I think it's working but want to close the loop w/ you too

**Comment by breville** [comment]
@ryansloan No repro for me right now.

**Comment by ryansloan** [comment]
I can no longer get a repro in any browser on staging, but can repro easily on prod (no DTP yet.) Closing and will verify on prod after deploy as well.
