### ISSUE TITLE
High volume of JS Errors in edge

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#390]
Our most common error is on /s/dance/stage/1/puzzle/1 and it is `Unable to get property 'x' of undefined or null reference` The vast majority are in Edge, with quite a bit in IE (very few in other browsers)

![Newrelic screenshot](https://user-images.githubusercontent.com/1669271/48515869-d37e6280-e816-11e8-85bd-7d3cf2cd6d60.png)

I can't repro but @boatmarina may have a repro on her machine (though the error message looks a bit different):
![image 14](https://user-images.githubusercontent.com/1669271/48516012-2e17be80-e817-11e8-8507-5a0e68c1982f.png)

The errors seen in this ^ screenshot appear before the user has interacted with the puzzle, when the video is loading.

**Comment by islemaster** [comment]
!!! `base.js` is https://s.ytimg.com/yts/jsbin/player-vflYuqTT6/en_US/base.js - which is part of the YouTube video player, not even our code.

**Comment by davidsbailey** [comment]
@boatmarina , what specific version of Edge and Windows are you using?

**Comment by davidsbailey** [comment]
The particular error Ryan reported does not appear to be specific to dance. It also appears on farmer and artist levels. I am not able to get a repro in saucelabs or a VM using a variety of Edge/IE versions. If anyone else has access to a windows machine, it could be useful to just click around and eventually complete the first dance level on Edge or IE and see if the exact error above occurs.

**Comment by boatmarina** [comment]
i'm running Windows 10 and Edge 42 (Microsoft Edge 42.17134.1.0)

FWIW, i'm not seeing the errors anymore so maybe this is no longer an issue?
![image](https://user-images.githubusercontent.com/33850843/48593192-9393aa00-e900-11e8-954b-9aa8625ca30c.png)

**Comment by boatmarina** [comment]
went to level 1 and saw this error pop up after first video window was closed:
![image](https://user-images.githubusercontent.com/33850843/48593226-bd4cd100-e900-11e8-9482-b617e91b8137.png)

**Comment by epeach** [comment]
Trying to repro - I'm on an older version of Edge (v. 40) and am not seeing these errors. Instead I'm seeing CORS related errors. Going to update my machine and see if I can repro the errors.

**Comment by boatmarina** [comment]
i'm no longer repro'ing this

**Comment by islemaster** [comment]
Thanks for the investigation Erin!  At this point we're satisfied (thanks to your research) that this isn't having a negative effect on users and we don't need to worry about it.  Wontfixing!
