### ISSUE TITLE
blank HoC script showing in assignment selector

### ISSUE THREAD

**Issue by davidsbailey** [code-dot-org/dance-party#391]
it looks like we have a blank script named `2018hoc-ab` which is not hidden but also not categorized in the assignment selector menu:

<img width="585" alt="screen shot 2018-11-14 at 2 33 15 pm" src="https://user-images.githubusercontent.com/8001765/48517184-5ce36400-e81a-11e8-93b7-c211e5962121.png">

Perhaps it should be hidden?

**Comment by ryansloan** [comment]
Good catch Dave. This was definitely not supposed to be released - it was someone's early prototype. I updated on levelbuilder
