### ISSUE TITLE
Potential issues with Chrome V71 

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#392]
In Chrome 71, there are changes coming to the sound autoplay policies coming in Chrome in December. This is timed near the Hour of Code, so we think it has the potential to break some things.

We should start by trying the tutorial in dev builds of Chrome 71 to get a handle on what (if anything) needs to change.

This isn't an emergency (things might be ok) but it is time-sensitive - if there's work for us to do we'd like to understand exactly what it is as soon as possible. 

The new version of chrome is scheduled to ship as "stable" on December 4, during CS Ed Week

**Comment by joshlory** [comment]
Ryan & I tested this out in Chrome Canary 72 and saw no issues with chrome://flags/#enable-autoplay-ignore-web-audio enabled.  @ryansloan any further due diligence you think we should do before closing out?

**Comment by ryansloan** [comment]
I think we can close the issue out since it seems ok. Going to install the canary and use it a bunch just to keep an eye, but I think we are in good shape.
