### ISSUE TITLE
Shared levels are missing the big "How It Works" button

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#395]
Other Hour of Code shares have a nice big "How It Works" button to encourage people to look at the code:
![screenshot 2018-11-15 11 20 33](https://user-images.githubusercontent.com/2205926/48521444-a094a700-e8c8-11e8-9616-74d4b3317ef4.png)

But it's missing for Dance Party:
![screenshot 2018-11-15 11 21 13](https://user-images.githubusercontent.com/2205926/48521445-a12d3d80-e8c8-11e8-87f8-5ac04142399b.png)

**Comment by boatmarina** [comment]
same as #123 ? or is that a different flag?

**Comment by breville** [comment]
I'm not sure what drives those buttons vs. this one, but it's certainly a different piece of resulting UI.

**Comment by boatmarina** [comment]
pulling this one in instead of #123
