### ISSUE TITLE
Puzzle 9: instructions need updating

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#397]
Instructions say: `This program uses the music's "bass" volume (the low sounds) to control one dancer's height.`

But it should now be: `This program uses the music's "treble" volume (the high sounds) to control one dancer's height.`

Because it's like this:

![screenshot 2018-11-15 21 39 54](https://user-images.githubusercontent.com/2205926/48547545-027ffb80-e91f-11e8-812c-98979ec94893.png)

**Comment by ryansloan** [comment]
fixed in levelbuilder, scooped today.
