### ISSUE TITLE
Validation on Level 2 always succeeds

### ISSUE THREAD

**Issue by poorvasingal** [code-dot-org/dance-party#403]
If I just run the starter code, I will pass the level.

**Comment by bpcb** [comment]
+1

**Comment by joshlory** [comment]
@davidsbailey when you update the validation code, can you update the integration test as well?  Thank you!!

**Comment by davidsbailey** [comment]
Yep, can you point me to it @joshlory ?

**Comment by joshlory** [comment]
Yep!  The test is here:

https://github.com/code-dot-org/dance-party/blob/3293d9c00869dc03f2d608c9974b106d33048ce8/test/integration/hourOfCodeTest.js#L24-L30

And the validation code for the level fixture is kept here:

https://github.com/code-dot-org/dance-party/blob/3293d9c00869dc03f2d608c9974b106d33048ce8/levels/hourOfCode.js#L35-L54

(We don't keep the fixtures in sync with Level Builder, maybe we should...  The idea was that we'd add new fixtures as needed, but not necessarily delete old ones unless we no longer want to test that behavior.  The integration tests run pretty fast, with `WATCH=1 npm run test:integration`).

**Comment by davidsbailey** [comment]
fix for tests: https://github.com/code-dot-org/dance-party/pull/445
