### ISSUE TITLE
Crash on Safari 8.0 (Yosemite)

### ISSUE THREAD

**Issue by islemaster** [code-dot-org/dance-party#406]
Dance Party frequently crashes on load in our SafariYosemite tests on our test environment (running on a Mac Mini with 2.0G RAM).

This is a low-ish priority because:
- We can't repro in any of our other environments using the same device and test configurations.
- Safari 8.0 represents a fairly small slice of our audience (20x smaller than IE11 usage).

I'm disabling these tests for now to minimize test noise and speed up test runs, so opening this issue to make sure we revisit the problem eventually.

**Comment by boatmarina** [comment]
looking at your comments Brad, i think we can close this as won't fix.  doing so.  reopen if you disagree!
