### ISSUE TITLE
Age dialog on standalone Dance Party project takes me to /view page instead of /edit page

### ISSUE THREAD

**Issue by poorvasingal** [code-dot-org/dance-party#408]
Repro:

- While signed out, create a new Dance Party project (I used the Create dropdown for this or just typed in studio.code.org/projects/dance in the URL bar)
- You should get prompted for your age. Enter a age.

Expected: You can create a project now.
Actual: You're taken to the /view page for the project.

**Comment by boatmarina** [comment]
I repro this too.  bad bug

**Comment by boatmarina** [comment]
@madelynkasula another potential solution (not sure if this simpler), but perhaps we should (for the short-term) only offer the under 13 list of songs for stand alone projects - I'd be OK with that if other solutions are too risky.  @Bjvanminnen may also have other ideas for how to deal with this?

**Comment by simplycloud** [comment]
fix went in build last night; confirming and then will close.

**Comment by madelynkasula** [comment]
Fixed by [code-dot-org#26154](https://github.com/code-dot-org/code-dot-org/pull/26154)
