### ISSUE TITLE
Level 1 of Dance Party stage 2 isn't translateable

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#411]
idea to address this:  put the levels from stage 2 into a separate script and link to this version from /dance and congrats page when in another language

**Comment by boatmarina** [comment]
I think most straightforward solution to this is to make a separate script for dance-extras that's the 'intl' version and link to this when /dance and /congrats pages are in non-english.  we'd also have to remember to hook up the scaling flag to this version of the script

**Comment by simplycloud** [comment]
Marina following up on options here so will assign once we have a product decision.
