### ISSUE TITLE
"View more" dance projects button doesn't show more

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#413]
Visit https://studio.code.org/projects/public.  
View more  dance projects to reveal the `"+ View more"` button at bottom.
Click it.

Result: nothing more is revealed.

Also: The URL is this: `https://studio.code.org/api/v1/projects/gallery/public/dance/100/2018-11-15T23:35:06.000+00:00`  Is this a real URL?

**Comment by boatmarina** [comment]
i don't repro this - i'm on chrome and PC.  when i click view more i see more projects pop in.  do you repro this every time @breville

**Comment by breville** [comment]
I reproed several times before reporting, but now it seems to be working.

**Comment by boatmarina** [comment]
great!  marking as won't fix.
