### ISSUE TITLE
Missing social share buttons

### ISSUE THREAD

**Issue by islemaster** [code-dot-org/dance-party#415]
**Given** I am using Firefox 63.0 on Ubuntu 18.04.1
**And** I am signed in _as a teacher_ with my personal email address through Google OAuth
**When** I go to [my dance party project](https://studio.code.org/projects/dance/pQUEo0IA53naoqu0FJTYtcI-efWs5bNxKK46_ri-LZ4/edit)
**And** I click the "Share" button in the header
**Then** I expect to see Twitter and Facebook share links
**But** I see this:
![image](https://user-images.githubusercontent.com/1615761/48593357-3a784600-e901-11e8-9197-3c582e897891.png)

**Comment by islemaster** [comment]
I do see the buttons when
- Using Chrome 70.0
- And signed in as a teacher with my work email address through Google OAuth
![image](https://user-images.githubusercontent.com/1615761/48593433-aeb2e980-e901-11e8-8685-c23bf55f9e3c.png)

**Comment by islemaster** [comment]
The age for this account is correct:
```
[production] dashboard > brad.age
=> "21+"
```

**Comment by breville** [comment]
Do our reachability checks for fb & twitter work?  

There should be network requests for https://facebook.com/favicon.ico & https://twitter.com/favicon.ico

**Comment by islemaster** [comment]
Console shows:

![screenshot from 2018-11-16 16-00-24](https://user-images.githubusercontent.com/1615761/48653284-06f8f280-e9b9-11e8-9edf-6143f4f33c48.png)

That `[more]` link takes one to https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Tracking_Protection which explains

> Starting in version 42, Firefox Desktop and Firefox for Android include built-in tracking protection. In Private Browsing windows (tabs, in Firefox for Android), Firefox will block content loaded from domains that track users across sites.

Looks like both Facebook and Twitter made Firefox's list of sites to block when tracking protection is enabled.

Sure enough, disabling tracking protection causes our social share links to show up.

![image](https://user-images.githubusercontent.com/1615761/48653349-740c8800-e9b9-11e8-8fc7-1423b47fcd10.png)

**Comment by islemaster** [comment]
Here's the block list: https://disconnect.me/trackerprotection/blocked

I'd say there's nothing we can/should do about this right now.
