### ISSUE TITLE
GPU Rasterization rendering glitches when using touch

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#416]

**Comment by joshlory** [comment]
Only repros on certain Chromebooks, maybe related to their chipset?  Need to reduce the repro we have to a minimal SVG + JS.

**Comment by joshlory** [comment]
Might be related to https://bugs.chromium.org/p/chromium/issues/detail?id=691262.

**Comment by joshlory** [comment]
Candidate fix is in.
