### ISSUE TITLE
unused code still runs when shared

### ISSUE THREAD

**Issue by simplycloud** [code-dot-org/dance-party#418]
unattached blocks run as if they are connected to `when run` when the project is shared and/or view-only.

![image](https://user-images.githubusercontent.com/8651388/48642753-9fc84780-e992-11e8-8b4b-d3777141d07c.png)

![image](https://user-images.githubusercontent.com/8651388/48642771-a8b91900-e992-11e8-8017-9724c767e308.png)

**Comment by ryansloan** [comment]
closing since this is a dupe #417
