### ISSUE TITLE
New stress test scenarios over all backgrounds, etc.

### ISSUE THREAD

**Issue by islemaster** [code-dot-org/dance-party#438]
We want to know about these crashes even if we're going to wontfix them.

**Comment by islemaster** [comment]
Getting some initial results from the new backgrounds.  Here's a performance ranking by framerate. Looks like we should do some optimization to the top 8 or so.
![image](https://user-images.githubusercontent.com/1615761/48822319-7a7c6600-ed11-11e8-954c-be9ea39e5c2a.png)

**Comment by simplycloud** [comment]
will close, we now have stress tests for all backgrounds. thanks brad!
