### ISSUE TITLE
Kaleidoscope and Fireworks background effects don't work on Safari

### ISSUE THREAD

**Issue by islemaster** [code-dot-org/dance-party#439]
The kaleidoscope effect (introduced in https://github.com/code-dot-org/dance-party/pull/396) does not seem to work on Safari (found by @cpirich) - we are just seeing a dark gray background.

Probably not the root cause but worth considering while this is addresed - in https://github.com/code-dot-org/dance-party/pull/26 Chris describes a memory leak he found in Safari when using `p5.createGraphics` in a background effect.  Kaleidoscope also uses `p5.createGraphics` so there might be a risk of Safari memory leak here too.

FYI @joshlory

**Comment by joshlory** [comment]
I get a console error:

> Exception with thrown value: TypeError: Attempted to assign to readonly property.

When trying to set `webkitBackingStorePixelRatio` on `p5.drawingContext`.

**Comment by joshlory** [comment]
We may be able to fix by changing these lines:

```js
this.shapes.pixelDensity(1);
// ...
this.hex.pixelDensity(1);
```

to:

```js
this.shapes._pixelDensity = 1;
// ...
this.hex._pixelDensity = 1;
```

**Comment by joshlory** [comment]
@simplycloud were you still planning to take this or do you want me to fix?

**Comment by simplycloud** [comment]
@joshlory i haven't got to these yet. can you grab this today?
