### ISSUE TITLE
Typo "vertial position" in block dropdown

### ISSUE THREAD

**Issue by jakebrbell** [code-dot-org/dance-party#444]
In the property dropdown for the `[SPRITE] stops [PROPERTY] following [RANGE]` block, the word vertical is misspelled as "vertial"

![screen shot 2018-11-19 at 2 25 41 pm](https://user-images.githubusercontent.com/12363478/48739777-d956b800-ec09-11e8-81a1-fda82d218708.png)

**Comment by ryansloan** [comment]
I updated in levelbuilder, we will need to sync the `Dancelab_stopMapping` block
