### ISSUE TITLE
"Unhandled promise rejection PNG blob required." on FF/Safari

### ISSUE THREAD

**Issue by Bjvanminnen** [code-dot-org/dance-party#451]
Go to https://studio.code.org/s/dance/stage/1/puzzle/2 and hit run.

On Chrome, things look fine. On FF and Safari I get an error

![image](https://user-images.githubusercontent.com/1767466/48861046-6e2af400-ed77-11e8-810e-a09e3ef37168.png)

Not yet clear to me if there's a user bad here. I also see the same error on other levels.

The error appears to be coming from https://github.com/code-dot-org/code-dot-org/blob/staging/apps/src/code-studio/initApp/project.js#L1318

**Comment by Bjvanminnen** [comment]
It looks like that error was added as part of this recent commit by @madelynkasula https://github.com/code-dot-org/code-dot-org/commit/d94c8c3285c663d5abcb6fda689104cbb7cf728e and she might be able to better speak to how much we care.

**Comment by madelynkasula** [comment]
good find! no user bad here, just noisy errors thankfully, but i'll add a guard to get rid of them.

**Comment by simplycloud** [comment]
@madelynkasula is this something you want to fit in prior to CSED week or do I mark this as post HOC?

**Comment by madelynkasula** [comment]
@simplycloud this can be post HOC

**Comment by madelynkasula** [comment]
fixed by [code-dot-org#26213](https://github.com/code-dot-org/code-dot-org/pull/26213)
