### ISSUE TITLE
Falling emoji backgrounds perform poorly on mobile Safari

### ISSUE THREAD

**Issue by islemaster** [code-dot-org/dance-party#452]
Initial results from stress testing against the new backgrounds show performance issues in a few of them - particularly ones where we're drawing lots of 'emoji' to the screen:

- raining_tacos
- falling_rainbows
- pizzas
- music_notes
- pineapples
- hearts
- falling_poop

![image](https://user-images.githubusercontent.com/1615761/48822319-7a7c6600-ed11-11e8-954c-be9ea39e5c2a.png)

One of the things they have in common is that they're repeating the same drawing operations many times instead of drawing once to an offscreen canvas and copying to the playspace.  We think this will be a fairly straightforward fix.

**Comment by breville** [comment]
Is there a reason we don't we just load these images from a small PNG spritesheet?

**Comment by simplycloud** [comment]
this is addressed in PR https://github.com/code-dot-org/dance-party/pull/464

**Comment by simplycloud** [comment]
this is now resolved.
