### ISSUE TITLE
Adding more backgrounds causes "random" in the dropdown to break for old solutions

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#469]
"Random" was previously selected, but when we added more backgrounds it changed the key:
<img width="822" alt="screen shot 2018-11-26 at 9 30 48 am" src="https://user-images.githubusercontent.com/1669271/49031149-0bae6b00-f15e-11e8-91d6-41d06fb426ae.png">

Random arg is now:
```
["(Random)",
          "['disco', 'color_cycle', 'rainbow', 'diamonds','snowflakes','splatter','swirl','spiral','starspace'][randomInt(0,8)]"]
```

**Comment by uponthesun** [comment]
Talked to @davidsbailey, and he suggested defining a new block to have the updated value, keeping the old one for backwards compatibility, and updating all of the levels. He'd made a similar change here:

https://github.com/code-dot-org/code-dot-org/pull/26206

**Comment by ryansloan** [comment]
@uponthesun We will definitely be changing this list in the future, though we aren't planning to change the user-facing list again in the HOC timeframe (it will change on our development environments, but we aren't planning to ship more than one more revision of the list publicly for HOC). 

I think if it's possible, the best thing to do is to do it the right way and remove the list and random int selection from the key and give it a `rand` key or something like that. Is that a feasible option for Hour of Code? Or do we need to continue to use the enumerated list as key?

**Comment by uponthesun** [comment]
Talked with @ryansloan - I'll try to implement the "right" fix (adding the "rand" key and adding the list of backgrounds into the dance party code) and have that ready for Thursday.

**Comment by ryansloan** [comment]
Spec for what we're going to do here:

1) Ryan will create a new `setBackgroundEffectWithPalette` block on levelbuilder with an option in the list with display name "(Random)" and key "rand"

2) @uponthesun will update `DanceParty.setBackgroundEffect` to check for `effect=="rand"`, and if so select a random background from this hardcoded list:
```
['circles','color_cycle', 'diamonds', 'disco_ball', 'fireworks', 'swirl', 'kaleidoscope', 'lasers', 'splatter', 'rainbow', 'snowflakes', 'text', 'galaxy', 'sparkles', 'spiral', 'disco', 'stars']
```
I think @islemaster would be a great person to pair with on this, he's done a bunch of work in this repo. Let me know if you have any questions!

**Comment by ryansloan** [comment]
(Sorry, deleted an earlier comment while we iterated on the plan)
Spec for what we’re going to do here:
[x] create a new `setBackgroundEffectWithPalette` block with an option in the list with display name “(Random)” and key “rand” (**done on levelbuilder**)
[ ] (Ryan) create a new `setForegroundEffectExtended` block with an option in the list with display name “(Random)” and key “rand”
[ ] Create `DanceParty.setBackgroundEffectWithPalette` wrapper function that, if `effect=="rand"` selects a random background effect and passes it into setBackgroundEffect
[ ] Create `DanceParty.setForegroundEffectExtended` wrapper function that, if `effect=="rand"` selects a random foreground effect and passes it into setForegroundEffect
[ ] (Ryan) Update all levels in levelbuilder to use the new `setBackgroundEffectWithPalette` block and `setForegroundEffectExtended`

The background list to use is: 
```
['circles','color_cycle', 'diamonds', 'disco_ball', 'fireworks', 'swirl', 
'kaleidoscope', 'lasers', 'splatter', 'rainbow', 'snowflakes', 'text', 
'galaxy', 'sparkles', 'spiral', 'disco', 'stars']
```
The foreground list to use is:

The foreground list to use is:
```
['bubbles', 'confetti', 'hearts_red', 'music_notes', 'pineapples', 
'pizzas', 'smiling_poop', 'rain', 'floating_rainbows', 'smile_face', 
'spotlight', 'color_lights', 'raining_tacos']
```

@islemaster and @uponthesun I think we're going to try to get this checked in for tomorrow's merges, so can you two please figure out the best way to go about this between the two of you? Let me know if you have any questions!

**Comment by islemaster** [comment]
See `setBackgroundEffectWithPalette` and `setForegroundEffectExtended` introduced in https://github.com/code-dot-org/dance-party/pull/499.

**Comment by simplycloud** [comment]
fixed with the launch of the new block.
