### ISSUE TITLE
Uptown Funk out of sync?

### ISSUE THREAD

**Issue by mikeharv** [code-dot-org/dance-party#470]
The clap animation doesn't line up to the claps in the song. Project example: https://studio.code.org/projects/dance/wAPAhTyTv9yhDziVxi9PdSMLSNEfYvOtbMyWj2jlcMI

**Comment by boatmarina** [comment]
This is an example of something we can't get right for all songs without a lot more work - it depends on what kind of song it is and whether the "beat" is on the 1 or on the 2.  we optimized for the most common "type" of song, but some songs have the beat in a place that doesn't align with the peak of the animation.  In an alternate universe, we could have divided songs into different types and made different animations based on song type, but we didn't take the time to do that.
