### ISSUE TITLE
Finish dialog is missing the send to phone option

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#483]
The share dialog has the send to phone button, but the finish dialog does not (both for under and over 13 year olds):
![image](https://user-images.githubusercontent.com/33850843/49101189-74631980-f22a-11e8-8126-0798726d02f3.png)

**Comment by madelynkasula** [comment]
fixed by [code-dot-org#26226](https://github.com/code-dot-org/code-dot-org/pull/26226)
