### ISSUE TITLE
Windows 7 + IE 11 shows "not supported" banner

### ISSUE THREAD

**Issue by jmkulwik** [code-dot-org/dance-party#484]
Technical requirements page shows "supported": https://support.code.org/hc/en-us/articles/202591743

**Comment by breville** [comment]
Unable to repro on SauceLabs.  Have asked @jmkulwik to investigate whether we are hitting [this line](https://github.com/code-dot-org/code-dot-org/blob/staging-next/apps/src/util/unsupportedBrowserWarning.js#L20) or something else nearby.  In that code, IE11 should only show "not supported" for App Lab levels.

**Comment by boatmarina** [comment]
we have 3.5% of our users on windows 7 & IE
![image](https://user-images.githubusercontent.com/33850843/49243556-7eb81b80-f3c2-11e8-81d4-29b1e84a8fc2.png)

**Comment by simplycloud** [comment]
fix merged, closing.
