### ISSUE TITLE
nativeAPI.getTime("measures") should return integers only

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#5]
I think the version of this API in the old helper library returned the floor of the measure count. I'm not 100% sure what is desired here, but our validation logic was largely written expecting integers (for example, we do `nativeAPI.getTime("measures") % 4`)

**Comment by ryansloan** [comment]
@mrjoshida would like to get your thoughts on this before we change.

**Comment by mrjoshida** [comment]
I'd like `getTime` to return a float (which is how it behaved in the original library) to keep the ceiling high (that way I can react to half measures). Most validation logic shouldn't need ints (usually we're just checking that you've passed a certain amount of measures), so if we need them in some cases I'd rather get the floor in validation.

**Comment by mrjoshida** [comment]
I’m not super committed, I could see it going either way. I haven’t really used the block in anything so I don’t have a great feel for the most natural use case.

**Comment by ryansloan** [comment]
We'll keep it as-is. Validation was fine once I realized it returned a float, so if we're not certain we'd want to limit it, this gives us more flexibility.
