### ISSUE TITLE
Artist handle isn't populating in Finish dialog, but works in Share dialog

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#503]
Finish dialog:
![image](https://user-images.githubusercontent.com/33850843/49127816-b7021180-f27d-11e8-8bd8-eaf49be04861.png)

Share dialog:
![image](https://user-images.githubusercontent.com/33850843/49127829-c2553d00-f27d-11e8-9b33-a4bb63046e6d.png)

**Comment by boatmarina** [comment]
Don't recall who worked on this.  I think it was @epeach ?

**Comment by Erin007** [comment]
It was me  🙂

**Comment by Erin007** [comment]
https://github.com/code-dot-org/code-dot-org/pull/26244

**Comment by Erin007** [comment]
<img width="689" alt="screen shot 2018-11-29 at 10 04 16 am" src="https://user-images.githubusercontent.com/12300669/49241959-2f6fec00-f3be-11e8-84bf-0e5ddd44ab15.png">
