### ISSUE TITLE
"after N measures" and "every N measures" events start too early 

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#51]
Current: they begin in measure N
Expected: they begin in measure N+1

**Comment by mrjoshida** [comment]
Note that this off by 1 error is also impacting `every n measures` (eg `every 2 measures` fires on 1, 2, 4, 6...)

**Comment by ryansloan** [comment]
@mrjoshida we are planning to do this week

**Comment by breville** [comment]
As part of this fix, we will change the events to fire after the first duration has passed.  e.g. "every 4 measures" will fire on measures `5, 9, 13` rather than the currently-intended `1, 5, 9, 13`.
