### ISSUE TITLE
Perpetual spinner if animation download is unsuccessful from the Finish Dialog

### ISSUE THREAD

**Issue by Erin007** [code-dot-org/dance-party#519]
Sort of similar to #489 

If there is an unsuccessful animation download from the FinishDialog you get a perpetual spinner and no error message even after the attempts to fetch the animation fail (it tries 30 times). The Share Dialog eventually gives you a handy error message.  We should at least have the same error message in the Finish Dialog as in the Share Dialog. 

![forever-spin](https://user-images.githubusercontent.com/12300669/49183860-d0a16880-f312-11e8-9f17-65bc6c746568.gif)

**Comment by simplycloud** [comment]
@Hamms thoughts on this? is this something we can resolve easily? in speaking with @Erin007 we have already addressed this in one of the code paths (the share workflow, i believe).

**Comment by simplycloud** [comment]
fix merged in deployment earlier today.
