### ISSUE TITLE
Snow background doesn't change w/ color scheme

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#528]
no matter what color scheme i choose, i get the same visual for snow:

![image](https://user-images.githubusercontent.com/33850843/49242053-807fe000-f3be-11e8-9424-d23cbb273e60.png)

neon:
![image](https://user-images.githubusercontent.com/33850843/49242073-8b3a7500-f3be-11e8-8093-5cf1966451e0.png)

**Comment by simplycloud** [comment]
@epeach can we add the palette to the background and leave the snow white?

**Comment by epeach** [comment]
@simplycloud Yes, what palette color do we want to use? The 'middlest' palette color?

**Comment by simplycloud** [comment]
yeah, this looks good. thanks @epeach !
