### ISSUE TITLE
Maximum callstack exceeded error when trying to duplicate some blocks

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#62]
# Repro steps: 
**Build the following program:**
<img width="567" alt="screen shot 2018-10-29 at 3 55 11 pm" src="https://user-images.githubusercontent.com/1669271/47685301-3921ec00-db93-11e8-85a7-673c05ac1642.png">

Click the "Make a new" block inside the conditional (the one the arrow is pointing to) and then hit Command+C and Command+V

**Observe**: the blocks in the blockspace disappear:
<img width="1002" alt="screen shot 2018-10-29 at 3 57 21 pm" src="https://user-images.githubusercontent.com/1669271/47685325-5656ba80-db93-11e8-873d-85abddc53e20.png">

And there are JS errors:
<img width="918" alt="screen shot 2018-10-29 at 3 51 48 pm" src="https://user-images.githubusercontent.com/1669271/47685355-76867980-db93-11e8-91ee-0ef9ffb35fa5.png">

**Comment by joshlory** [comment]
Great bug!  This likely regressed in https://github.com/code-dot-org/blockly/pull/128.  I'm going to reduce this test case and get it added to the Blockly repo, then look at a fix.

**Comment by islemaster** [comment]
I've repro'd this case and can watch the infinite loop happen in slow motion - the newly-copied block is bumping the existing blocks, then vice-versa, ad infinitum.

![infinibump](https://user-images.githubusercontent.com/1615761/48866147-9ff78700-ed86-11e8-912f-edec154b702a.gif)

Finding the exact logic error allowing this loop (and working out how we can avoid this mistake in the future) is going to be trickier...

**Comment by islemaster** [comment]
Fix is ready for review.
