### ISSUE TITLE
Random Background causes white screen

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#64]

**Comment by joshlory** [comment]
Added https://github.com/code-dot-org/dance-party/commit/5ea3f6d6af1063fb4e2a6fddfda1006e078073aa to address, but you'll want to update https://levelbuilder-studio.code.org/blocks/Dancelab_setBackgroundEffect/edit to call `randomInt` instead of `randomNumber`.

**Comment by joshlory** [comment]
(After 0.0.12 is deployed to Level Builder.)

**Comment by ryansloan** [comment]
Verified fix!
