### ISSUE TITLE
Pass in localizable failure strings

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#69]
We have defined specific error strings for failure messages in Dance Party Validation. See this levelbuilder screenshot:

<img width="1061" alt="screen shot 2018-10-30 at 9 45 37 am" src="https://user-images.githubusercontent.com/1669271/47734926-9caa2900-dc28-11e8-9f38-02f40335a58f.png">

We have also put these strings into [the dance app's string file](https://github.com/code-dot-org/code-dot-org/blob/staging/apps/i18n/dance/en_us.json) We now need to support referencing these localized strings in validation code.

**Comment by madelynkasula** [comment]
PR opened in [code-dot-org](https://github.com/code-dot-org/code-dot-org/pull/25680) repo. I'll close this issue upon approval/merge.

**Comment by madelynkasula** [comment]
The [PR](https://github.com/code-dot-org/code-dot-org/pull/25697) that adds this functionality was merged, so preemptively closing this issue!
