### ISSUE TITLE
Share Links from Freeplay are inaccessible for some accounts

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#76]
Share links from the freeplay level aren’t working when I’m signed into my code.org account (ryan@). The account is not an admin account, and can confirm that gamelab share links work. Here is an example https://studio.code.org/projects/dance/K3Hhv5c6wh1iSLTIk8lPMUOqRe_G6W-8du3npxoILL8
I get Page Not Found:
<img width="1431" alt="screen shot 2018-10-30 at 11 24 57 am" src="https://user-images.githubusercontent.com/1669271/47740998-755a5880-dc36-11e8-9cd6-17516eb4ffbf.png">

I can open this share link from a personal account.

**Comment by islemaster** [comment]
Things I've learned:

**This project looks like it was created while signed out** - it's storage id has no owner, and it raises an exception when `User.find_channel_owner` is called.
```
PEGASUS_DB[:user_storage_ids].where(id: <hidden>).first
=> {:id=><hidden>, :user_id=>nil}

User.find_channel_owner 'K3Hhv5c6wh1iSLTIk8lPMUOqRe_G6W-8du3npxoILL8'
Traceback (most recent call last):
       13: from ./bin/rails:9:in `<main>'
       12: from ./bin/rails:9:in `require'
       11: from /var/lib/gems/2.5.0/gems/railties-5.0.7/lib/rails/commands.rb:18:in `<top (required)>'
       10: from /var/lib/gems/2.5.0/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        9: from /var/lib/gems/2.5.0/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:78:in `console'
        8: from /var/lib/gems/2.5.0/gems/railties-5.0.7/lib/rails/commands/console_helper.rb:9:in `start'
        7: from /var/lib/gems/2.5.0/gems/railties-5.0.7/lib/rails/commands/console.rb:65:in `start'
        6: from (irb):7
        5: from /home/ubuntu/production/dashboard/app/models/user.rb:643:in `find_channel_owner'
        4: from /var/lib/gems/2.5.0/gems/composite_primary_keys-9.0.10/lib/composite_primary_keys/core.rb:27:in `find'
        3: from /var/lib/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/querying.rb:3:in `find'
        2: from /var/lib/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/relation/finder_methods.rb:66:in `find'
        1: from /var/lib/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/relation/finder_methods.rb:456:in `find_with_ids'
  ActiveRecord::RecordNotFound (Couldn't find User without an ID)
```

**Ryan's account that's getting a 404 has a bunch of permissions** including levelbuilder and project validator:
```
ryan.permissions.map(&:permission)
=> ["authorized_teacher", "levelbuilder", "plc_reviewer", "project_validator", "workshop_admin", "workshop_organizer"]
```

**Other users are able to load this project**

Theory:

We're rendering something in the view only for users with levelbuilder/project validator permission, that breaks when the project in question doesn't have an owner.  Testing by giving myself project validator permission on prod and checking this project, then I'll get a local repro.

**Comment by islemaster** [comment]
Confirmed: As a project validator I cannot load this project.  After removing project validator permission I can load it.

**Comment by islemaster** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix up last Dance Party level](https://trello.com/c/DjQ70KGk/1-fix-up-last-dance-party-level)
