### ISSUE TITLE
After N measures allows for non-number inputs

### ISSUE THREAD

**Issue by Bjvanminnen** [code-dot-org/dance-party#94]
![image](https://user-images.githubusercontent.com/1767466/47883070-ed688000-dde8-11e8-93ca-17504b50a186.png)

Result is a JS error on run.

Probably we should restrict the input to number values only.

**Comment by Bjvanminnen** [comment]
![image](https://user-images.githubusercontent.com/1767466/47884758-49ce9e00-ddef-11e8-82af-c64533e01fc0.png)

this block too

**Comment by Bjvanminnen** [comment]
The fact that I can put arbitrary text in here that gets executed as JS would leave me a little bit worried that there could be some sort of sandbox escape vector. I dont know enough about how the sandbox works to know whether that's true.

**Comment by islemaster** [comment]
Capturing Slack conversation:

> islemaster [17:12]
> `@ryansloan` Question re https://github.com/code-dot-org/dance-party/issues/94:
> Does restricting these fields to number input lower the ceiling on dance party because you can't reference a variable here?  Or do we already not support a variable in these cases? (edited)
> 
> ryansloan  [17:14]
> `@islemaster`  - good question. We don’t support variables there right now because it’s a textbox (not a socket)
> In blockly, you can only use variables when there’s a socket
>
> islemaster  [17:15]
> Related: Does number input work for all values of the second dropdown here (in particular I don't know about 'tint', is that a number?) (Edit: Looks like yes) (edited)
> Pasted image at 2018-11-06, 5:15 PM 
> 
> ryansloan  [17:23]
> yeah they are all numbers
